import {
  createBoard,
  deleteBoard,
  getInventoryRegions,
  getInventorySummary,
  listBoards,
  toggleBoardAvailability,
  updateBoard,
} from '../../../services/inventoryV4Service.js';

const inventoryBoardEvents = [
  'inventory.board.created',
  'inventory.board.updated',
  'inventory.board.availability.changed',
  'inventory.board.image.updated',
  'inventory.board.deleted',
];

export const inventoryAdapter = {
  domain: 'inventory',
  domainEvents: ['inventory.board.created', 'inventory.board.updated', 'inventory.board.availability.changed', 'inventory.board.image.updated', 'inventory.board.deleted'],
  permissions: ['inventory.read'],
  ttlMs: 60_000,
  fallbackPolicy: 'keep-last-valid',

  resources: [
    {
      key: 'inventory.summary',
      fetcher: getInventorySummary,
      ttlMs: 60_000,
      staleWhileRevalidate: 5 * 60_000,
      dependencies: ['inventory.boards'],
      dependents: ['dashboard.kpis', 'commercial.pipeline', 'alerts.list', 'reports.summary', 'operations.timeline'],
      domainEvents: ['inventory.board.created', 'inventory.board.updated', 'inventory.board.availability.changed', 'inventory.board.image.updated', 'inventory.board.deleted'],
      realtimeEvents: [...inventoryBoardEvents, 'inventory.summary.refreshed'],
      permissions: ['inventory.read'],
      fallbackPolicy: 'keep-last-valid',
      productionMockAllowed: false,
      debugLabel: 'Inventory summary',
    },
    {
      key: 'inventory.boards',
      fetcher: listBoards,
      ttlMs: 60_000,
      staleWhileRevalidate: 5 * 60_000,
      dependencies: [],
      dependents: ['inventory.summary', 'dashboard.kpis', 'commercial.pipeline', 'alerts.list', 'operations.timeline'],
      domainEvents: ['inventory.board.created', 'inventory.board.updated', 'inventory.board.availability.changed', 'inventory.board.image.updated', 'inventory.board.deleted'],
      realtimeEvents: [...inventoryBoardEvents],
      permissions: ['inventory.read'],
      fallbackPolicy: 'keep-last-valid',
      productionMockAllowed: false,
      debugLabel: 'Inventory boards',
    },
    {
      key: 'inventory.regions',
      fetcher: getInventoryRegions,
      ttlMs: 60_000,
      staleWhileRevalidate: 5 * 60_000,
      dependencies: ['inventory.boards', 'inventory.summary'],
      dependents: ['dashboard.kpis', 'commercial.pipeline', 'operations.timeline'],
      domainEvents: ['inventory.board.created', 'inventory.board.updated', 'inventory.board.availability.changed', 'inventory.board.image.updated', 'inventory.board.deleted'],
      realtimeEvents: [...inventoryBoardEvents],
      permissions: ['inventory.read'],
      fallbackPolicy: 'keep-last-valid',
      productionMockAllowed: false,
      debugLabel: 'Inventory regions',
    },
  ],

  mutations: [
    {
      key: 'inventory.board.update',
      domain: 'inventory',
      mutationFn: (payload) => updateBoard(payload.id, payload),
      permissions: ['inventory.update'],
      requiresAuth: true,
      requiresTenant: true,
      optimistic: true,
      optimisticUpdates: [{
        resourceKey: 'inventory.boards',
        updater: (boards = [], payload) => boards.map((board) => (
          board.id === payload.id ? { ...board, ...payload } : board
        )),
      }],
      rollbackPolicy: 'snapshot',
      reconcilePolicy: 'server-wins',
      invalidate: ['inventory.boards', 'inventory.summary'],
      invalidateDependents: true,
      conflictPolicy: 'server-wins',
      queueKey: (payload) => `inventory.board:${payload.id}`,
      debugLabel: 'Atualizar placa',
    },
    {
      key: 'inventory.board.toggleAvailability',
      domain: 'inventory',
      mutationFn: (payload) => toggleBoardAvailability(payload.id),
      permissions: ['inventory.update'],
      requiresAuth: true,
      requiresTenant: true,
      optimistic: false,
      rollbackPolicy: 'snapshot',
      reconcilePolicy: 'server-wins',
      invalidate: ['inventory.boards', 'inventory.summary'],
      invalidateDependents: true,
      conflictPolicy: 'server-wins',
      queueKey: (payload) => `inventory.board:${payload.id}`,
      debugLabel: 'Alternar disponibilidade da placa',
    },
    {
      key: 'inventory.board.create',
      domain: 'inventory',
      mutationFn: (payload) => createBoard(payload),
      permissions: ['inventory.create'],
      requiresAuth: true,
      requiresTenant: true,
      optimistic: false,
      invalidate: ['inventory.boards', 'inventory.summary', 'inventory.regions'],
      invalidateDependents: true,
      conflictPolicy: 'server-wins',
      debugLabel: 'Criar placa',
    },
    {
      key: 'inventory.board.delete',
      domain: 'inventory',
      mutationFn: (payload) => deleteBoard(payload.id),
      permissions: ['inventory.delete'],
      requiresAuth: true,
      requiresTenant: true,
      optimistic: false,
      rollbackPolicy: 'snapshot',
      invalidate: ['inventory.boards', 'inventory.summary', 'inventory.regions'],
      invalidateDependents: true,
      conflictPolicy: 'server-wins',
      queueKey: (payload) => `inventory.board:${payload.id}`,
      debugLabel: 'Excluir placa',
    },
  ],

  realtimeEvents: {
    'inventory.board.created':             ['inventory.summary', 'inventory.boards', 'inventory.regions', 'dashboard.kpis'],
    'inventory.board.updated':             ['inventory.summary', 'inventory.boards', 'inventory.regions', 'dashboard.kpis'],
    'inventory.board.availability.changed':['inventory.summary', 'inventory.boards', 'inventory.regions', 'dashboard.kpis', 'commercial.pipeline'],
    'inventory.board.image.updated':       ['inventory.boards', 'inventory.regions'],
    'inventory.board.deleted':             ['inventory.summary', 'inventory.boards', 'inventory.regions', 'dashboard.kpis'],
    'inventory.summary.refreshed':         ['inventory.summary', 'dashboard.kpis'],
    'inventory.region.updated':            ['inventory.boards', 'inventory.summary', 'inventory.regions'],
  },
};
