/* ═══════════════════════════════════════════════════════════════
   DASHBOARD MOCK DATA — V4 PAINEL
   Dados simulados para a Dashboard Executiva.
   Representam o estado operacional do inventário OOH InMidia.
═══════════════════════════════════════════════════════════════ */

import { OPERATIONAL_STATE } from '../../foundation/operationalStates.js';
import { SEVERITY }          from '../../foundation/severityLevels.js';
import { PRIORITY }          from '../../foundation/priorities.js';

/* ── KPIs PRINCIPAIS ─────────────────────────────────────────── */
export const DASHBOARD_KPIS = [
  {
    id:        'total-placas',
    label:     'Total de placas',
    value:     '847',
    raw:       847,
    icon:      'space_dashboard',
    trend:     '+12',
    trendUp:   true,
    period:    'vs. mês anterior',
    state:     OPERATIONAL_STATE.HEALTHY,
    highlight: false,
  },
  {
    id:        'placas-ocupadas',
    label:     'Placas ocupadas',
    value:     '661',
    raw:       661,
    icon:      'check_circle',
    trend:     '+34',
    trendUp:   true,
    period:    'vs. mês anterior',
    state:     OPERATIONAL_STATE.HEALTHY,
    highlight: false,
  },
  {
    id:        'placas-disponiveis',
    label:     'Disponíveis',
    value:     '186',
    raw:       186,
    icon:      'radio_button_unchecked',
    trend:     '-22',
    trendUp:   false,
    period:    'vs. mês anterior',
    state:     OPERATIONAL_STATE.WARNING,
    highlight: true,
  },
  {
    id:        'taxa-ocupacao',
    label:     'Taxa de ocupação',
    value:     '78,1%',
    raw:       0.781,
    icon:      'donut_large',
    trend:     '+4,2pp',
    trendUp:   true,
    period:    'vs. mês anterior',
    state:     OPERATIONAL_STATE.HEALTHY,
    highlight: false,
  },
  {
    id:        'receita-projetada',
    label:     'Receita projetada',
    value:     'R$ 284.750',
    raw:       284750,
    icon:      'attach_money',
    trend:     '+12%',
    trendUp:   true,
    period:    'vs. mês anterior',
    state:     OPERATIONAL_STATE.HEALTHY,
    highlight: false,
  },
  {
    id:        'contratos-ativos',
    label:     'Contratos ativos',
    value:     '143',
    raw:       143,
    icon:      'description',
    trend:     '+5',
    trendUp:   true,
    period:    'este mês',
    state:     OPERATIONAL_STATE.HEALTHY,
    highlight: false,
  },
  {
    id:        'contratos-vencendo',
    label:     'Contratos vencendo',
    value:     '11',
    raw:       11,
    icon:      'event_busy',
    trend:     '+3',
    trendUp:   false,
    period:    'próximos 30 dias',
    state:     OPERATIONAL_STATE.WARNING,
    highlight: true,
  },
  {
    id:        'alertas-criticos',
    label:     'Alertas críticos',
    value:     '3',
    raw:       3,
    icon:      'crisis_alert',
    trend:     '-1',
    trendUp:   true,
    period:    'vs. ontem',
    state:     OPERATIONAL_STATE.CRITICAL,
    highlight: true,
  },
];

/* ── DESEMPENHO REGIONAL ─────────────────────────────────────── */
export const REGIONAL_PERFORMANCE = [
  {
    id:               'sp',
    label:            'São Paulo',
    placasTotal:      312,
    placasOcupadas:   264,
    ocupacao:         0.846,
    receita:          128400,
    receitaFormatada: 'R$ 128.400',
    disponibilidade:  48,
    estado:           OPERATIONAL_STATE.HEALTHY,
    prioridadeComercial: PRIORITY.NORMAL,
    risco:            'baixo',
    tendencia:        'crescimento',
    heatLevel:        5,
  },
  {
    id:               'rj',
    label:            'Rio de Janeiro',
    placasTotal:      198,
    placasOcupadas:   148,
    ocupacao:         0.747,
    receita:          72600,
    receitaFormatada: 'R$ 72.600',
    disponibilidade:  50,
    estado:           OPERATIONAL_STATE.WARNING,
    prioridadeComercial: PRIORITY.HIGH,
    risco:            'médio',
    tendencia:        'estável',
    heatLevel:        4,
  },
  {
    id:               'mg',
    label:            'Minas Gerais',
    placasTotal:      124,
    placasOcupadas:   88,
    ocupacao:         0.710,
    receita:          43200,
    receitaFormatada: 'R$ 43.200',
    disponibilidade:  36,
    estado:           OPERATIONAL_STATE.HEALTHY,
    prioridadeComercial: PRIORITY.NORMAL,
    risco:            'baixo',
    tendencia:        'crescimento',
    heatLevel:        3,
  },
  {
    id:               'rs',
    label:            'Rio Grande do Sul',
    placasTotal:      89,
    placasOcupadas:   60,
    ocupacao:         0.674,
    receita:          24800,
    receitaFormatada: 'R$ 24.800',
    disponibilidade:  29,
    estado:           OPERATIONAL_STATE.DEGRADED,
    prioridadeComercial: PRIORITY.HIGH,
    risco:            'alto',
    tendencia:        'queda',
    heatLevel:        2,
  },
  {
    id:               'pr',
    label:            'Paraná',
    placasTotal:      76,
    placasOcupadas:   62,
    ocupacao:         0.816,
    receita:          28400,
    receitaFormatada: 'R$ 28.400',
    disponibilidade:  14,
    estado:           OPERATIONAL_STATE.HEALTHY,
    prioridadeComercial: PRIORITY.NORMAL,
    risco:            'baixo',
    tendencia:        'crescimento',
    heatLevel:        4,
  },
  {
    id:               'outros',
    label:            'Outras regiões',
    placasTotal:      48,
    placasOcupadas:   39,
    ocupacao:         0.813,
    receita:          15800,
    receitaFormatada: 'R$ 15.800',
    disponibilidade:  9,
    estado:           OPERATIONAL_STATE.HEALTHY,
    prioridadeComercial: PRIORITY.LOW,
    risco:            'baixo',
    tendencia:        'estável',
    heatLevel:        3,
  },
];

/* ── PROJEÇÃO DE RECEITA (12 meses) ──────────────────────────── */
export const REVENUE_PROJECTION = {
  meta:        320000,
  atual:       284750,
  projetado:   298000,
  percentMeta: 0.891,
  meses: [
    { label: 'Jun', valor: 198000, projetado: false },
    { label: 'Jul', valor: 215000, projetado: false },
    { label: 'Ago', valor: 228000, projetado: false },
    { label: 'Set', valor: 241000, projetado: false },
    { label: 'Out', valor: 256000, projetado: false },
    { label: 'Nov', valor: 271000, projetado: false },
    { label: 'Dez', valor: 284750, projetado: false },
    { label: 'Jan', valor: 298000, projetado: true  },
    { label: 'Fev', valor: 305000, projetado: true  },
    { label: 'Mar', valor: 312000, projetado: true  },
    { label: 'Abr', valor: 318000, projetado: true  },
    { label: 'Mai', valor: 320000, projetado: true  },
  ],
};

/* ── FUNIL COMERCIAL ─────────────────────────────────────────── */
export const COMMERCIAL_FUNNEL = [
  { id: 'leads',       label: 'Leads',             count: 284, valor: null,     conversao: null,  cor: 'var(--v4p-accent)' },
  { id: 'propostas',   label: 'Propostas enviadas', count: 128, valor: 'R$ 512.000', conversao: 0.45, cor: 'var(--v4p-info)' },
  { id: 'negociacao',  label: 'Em negociação',      count:  67, valor: 'R$ 268.000', conversao: 0.52, cor: 'var(--v4p-intelligence)' },
  { id: 'fechamento',  label: 'Fechamento',          count:  31, valor: 'R$ 124.000', conversao: 0.46, cor: 'var(--v4p-warning)' },
  { id: 'fechados',    label: 'Contratos fechados',  count:  18, valor: 'R$ 72.000',  conversao: 0.58, cor: 'var(--v4p-success)' },
];

/* ── PLACAS CRÍTICAS ─────────────────────────────────────────── */
export const CRITICAL_BOARDS = [
  {
    id:          'SP-2241',
    codigo:      'SP-2241',
    label:       'Paulista — Altura MASP',
    regiao:      'São Paulo',
    motivo:      'Sem atividade há 48h',
    impacto:     'R$ 4.200 parado',
    risco:       SEVERITY.HIGH,
    estado:      OPERATIONAL_STATE.CRITICAL,
    prioridade:  PRIORITY.URGENT,
    acao:        'Verificação de campo imediata',
    responsavel: 'Ops SP',
  },
  {
    id:          'RJ-0412',
    codigo:      'RJ-0412',
    label:       'Presidente Vargas — Centro',
    regiao:      'Rio de Janeiro',
    motivo:      'Estrutura com falha de iluminação reportada',
    impacto:     'R$ 2.800 em risco',
    risco:       SEVERITY.HIGH,
    estado:      OPERATIONAL_STATE.DEGRADED,
    prioridade:  PRIORITY.URGENT,
    acao:        'Manutenção programada para hoje',
    responsavel: 'Ops RJ',
  },
  {
    id:          'RS-0088',
    codigo:      'RS-0088',
    label:       'Av. Ipiranga — Porto Alegre',
    regiao:      'Rio Grande do Sul',
    motivo:      'Contrato vence em 3 dias sem renovação',
    impacto:     'R$ 1.900/mês em risco',
    risco:       SEVERITY.MEDIUM,
    estado:      OPERATIONAL_STATE.WARNING,
    prioridade:  PRIORITY.HIGH,
    acao:        'Contato com cliente amanhã',
    responsavel: 'Comercial RS',
  },
];

/* ── PLACAS OCIOSAS ──────────────────────────────────────────── */
export const IDLE_BOARDS = [
  {
    id:             'MG-0301',
    codigo:         'MG-0301',
    label:          'Afonso Pena — BH Centro',
    regiao:         'Minas Gerais',
    diasSemCampanha: 18,
    potencial:      'R$ 3.400/mês',
    categoria:      'Premium A',
    visibilidade:   'Alta',
    recomendacao:   'Acionar carteira de leads BH',
    oportunidade:   'Período pré-festivo favorável',
  },
  {
    id:             'SP-1089',
    codigo:         'SP-1089',
    label:          'Marginal Tietê — Km 24',
    regiao:         'São Paulo',
    diasSemCampanha: 12,
    potencial:      'R$ 5.800/mês',
    categoria:      'Premium A+',
    visibilidade:   'Muito alta',
    recomendacao:   'Priorizar em próxima proposta',
    oportunidade:   'Alta demanda no corredor',
  },
  {
    id:             'PR-0215',
    codigo:         'PR-0215',
    label:          'BR-376 — Km 91 Curitiba',
    regiao:         'Paraná',
    diasSemCampanha: 24,
    potencial:      'R$ 2.100/mês',
    categoria:      'Standard B',
    visibilidade:   'Média',
    recomendacao:   'Redução de preço de entrada',
    oportunidade:   'Corredor logístico ativo',
  },
  {
    id:             'RJ-0889',
    codigo:         'RJ-0889',
    label:          'Barra da Tijuca — Shopping',
    regiao:         'Rio de Janeiro',
    diasSemCampanha: 9,
    potencial:      'R$ 4.600/mês',
    categoria:      'Premium A',
    visibilidade:   'Alta',
    recomendacao:   'Contato com agências RJ',
    oportunidade:   'Sazonalidade verão ativa',
  },
];

/* ── CONTRATOS EM RISCO ──────────────────────────────────────── */
export const CONTRACTS_AT_RISK = [
  {
    id:             'CTR-2847',
    cliente:        'Grupo Azul Publicidade',
    regiao:         'São Paulo',
    valor:          'R$ 18.400/mês',
    vencimento:     '2026-05-26',
    diasRestantes:  7,
    risco:          SEVERITY.CRITICAL,
    impacto:        'R$ 220.800/ano',
    estado:         OPERATIONAL_STATE.CRITICAL,
    recomendacao:   'Reunião de renovação imediata',
    probabilidade:  'Alta — cliente satisfeito',
  },
  {
    id:             'CTR-2901',
    cliente:        'Distribuidora FastFood Nacional',
    regiao:         'Rio de Janeiro',
    valor:          'R$ 9.200/mês',
    vencimento:     '2026-06-03',
    diasRestantes:  15,
    risco:          SEVERITY.HIGH,
    impacto:        'R$ 110.400/ano',
    estado:         OPERATIONAL_STATE.WARNING,
    recomendacao:   'Proposta de expansão para MG',
    probabilidade:  'Média — em avaliação interna',
  },
  {
    id:             'CTR-2712',
    cliente:        'Agência Meridian Media',
    regiao:         'Minas Gerais',
    valor:          'R$ 6.800/mês',
    vencimento:     '2026-06-12',
    diasRestantes:  24,
    risco:          SEVERITY.MEDIUM,
    impacto:        'R$ 81.600/ano',
    estado:         OPERATIONAL_STATE.WARNING,
    recomendacao:   'Agendar revisão de campanha',
    probabilidade:  'Alta — sem sinal negativo',
  },
];

/* ── ALERTAS INTELIGENTES ────────────────────────────────────── */
export const SMART_ALERTS = [
  {
    id:          'alrt-001',
    titulo:      'Ponto SP-2241 sem sinal há 48h',
    descricao:   'Comunicação interrompida. Receita de R$ 4.200 em risco imediato.',
    severidade:  SEVERITY.CRITICAL,
    estado:      OPERATIONAL_STATE.CRITICAL,
    sla:         '2h',
    owner:       'Ops São Paulo',
    impacto:     'Alto',
    status:      'Aberto',
    acao:        'Verificação de campo acionada',
    timestamp:   '2026-05-19T07:14:00Z',
    lido:        false,
  },
  {
    id:          'alrt-002',
    titulo:      '3 contratos vencem em menos de 10 dias',
    descricao:   'CTR-2847, CTR-2901 e CTR-2712 sem confirmação de renovação.',
    severidade:  SEVERITY.HIGH,
    estado:      OPERATIONAL_STATE.WARNING,
    sla:         '8h',
    owner:       'Comercial',
    impacto:     'Financeiro — R$ 34.400/mês em risco',
    status:      'Em andamento',
    acao:        'Reuniões agendadas para hoje',
    timestamp:   '2026-05-19T08:00:00Z',
    lido:        false,
  },
  {
    id:          'alrt-003',
    titulo:      'Taxa de ocupação RS abaixo do limite',
    descricao:   'Rio Grande do Sul com 67,4% de ocupação — meta é 75%.',
    severidade:  SEVERITY.MEDIUM,
    estado:      OPERATIONAL_STATE.DEGRADED,
    sla:         '48h',
    owner:       'Comercial RS',
    impacto:     'Médio — R$ 8.200 de receita potencial parado',
    status:      'Monitorando',
    acao:        'Campanha de ativação regional iniciada',
    timestamp:   '2026-05-19T06:30:00Z',
    lido:        false,
  },
  {
    id:          'alrt-004',
    titulo:      'Consolidação de relatório mensal em andamento',
    descricao:   'Processamento iniciado às 09:00. Disponível em ~15 minutos.',
    severidade:  SEVERITY.INFO,
    estado:      OPERATIONAL_STATE.SYNCING,
    sla:         null,
    owner:       'Sistema',
    impacto:     'Baixo',
    status:      'Sincronizando',
    acao:        null,
    timestamp:   '2026-05-19T09:00:00Z',
    lido:        true,
  },
];

/* ── TIMELINE OPERACIONAL ────────────────────────────────────── */
export const ACTIVITY_TIMELINE = [
  { id: 'tl-01', tipo: 'contrato',   icone: 'description',  label: 'Contrato #2847 renovado com Grupo Azul',            regiao: 'São Paulo',  tempo: 'há 12 min', categoria: 'success'  },
  { id: 'tl-02', tipo: 'ativacao',   icone: 'location_on',  label: 'Ponto SP-1933 ativado — Campanha Verão 2026',       regiao: 'São Paulo',  tempo: 'há 28 min', categoria: 'info'     },
  { id: 'tl-03', tipo: 'alerta',     icone: 'warning',      label: 'Ponto RJ-0412 reportou falha de iluminação',        regiao: 'Rio de Janeiro', tempo: 'há 41 min', categoria: 'warning' },
  { id: 'tl-04', tipo: 'relatorio',  icone: 'bar_chart',    label: 'Relatório semanal exportado — Equipe SP',           regiao: 'São Paulo',  tempo: 'há 1h',     categoria: 'info'     },
  { id: 'tl-05', tipo: 'campanha',   icone: 'campaign',     label: 'Nova campanha cadastrada — Distribuidora FastFood', regiao: 'Nacional',   tempo: 'há 1h 22m', categoria: 'success'  },
  { id: 'tl-06', tipo: 'sincronizacao', icone: 'sync',      label: 'Sincronização automática concluída — 847 pontos',  regiao: 'Todos',      tempo: 'há 2h',     categoria: 'info'     },
  { id: 'tl-07', tipo: 'manutencao', icone: 'build',        label: 'Ponto MG-0112 retornou da manutenção',              regiao: 'Minas Gerais', tempo: 'há 2h 45m', categoria: 'success' },
  { id: 'tl-08', tipo: 'alerta',     icone: 'notifications',label: 'Alerta de ocupação baixa — Rio Grande do Sul',     regiao: 'Rio Grande do Sul', tempo: 'há 3h', categoria: 'warning' },
  { id: 'tl-09', tipo: 'contrato',   icone: 'description',  label: 'Contrato #2712 em análise de renovação',           regiao: 'Minas Gerais', tempo: 'há 3h 20m', categoria: 'warning' },
  { id: 'tl-10', tipo: 'campanha',   icone: 'campaign',     label: 'Campanha Agência Meridian — início de veiculação',  regiao: 'Minas Gerais', tempo: 'há 4h',    categoria: 'success'  },
];

/* ── OCUPAÇÃO POR CATEGORIA ──────────────────────────────────── */
export const OCCUPANCY_BY_CATEGORY = [
  { label: 'Premium A+', total: 48,  ocupados: 44, ocupacao: 0.917, cor: 'var(--v4p-success)' },
  { label: 'Premium A',  total: 142, ocupados: 124, ocupacao: 0.873, cor: 'var(--v4p-success)' },
  { label: 'Standard B+',total: 218, ocupados: 178, ocupacao: 0.817, cor: 'var(--v4p-accent)' },
  { label: 'Standard B', total: 289, ocupados: 214, ocupacao: 0.740, cor: 'var(--v4p-warning)' },
  { label: 'Econômico C',total: 150, ocupados: 101, ocupacao: 0.673, cor: 'var(--v4p-danger)' },
];
