/* ═══════════════════════════════════════════════════════════════
   OPERATIONS MOCK DATA — V4 PAINEL
   Dados operacionais em tempo real simulados.
═══════════════════════════════════════════════════════════════ */
import { OPERATIONAL_STATE } from '../../foundation/operationalStates.js';
import { SEVERITY }          from '../../foundation/severityLevels.js';

/* ── VISÃO GERAL OPERACIONAL ─────────────────────────────────── */
export const OPS_OVERVIEW = {
  totalPontos:       847,
  pontosAtivos:      661,
  pontosDisponiveis: 186,
  emManutencao:      18,
  reservados:        12,
  ocupacaoGlobal:    0.781,
  receitaAtiva:      284750,
  alertasRegionais:  4,
  sincronizacao:     OPERATIONAL_STATE.HEALTHY,
  ultimaAtualizacao: 'há 42 segundos',
};

/* ── MÓDULOS DO RUNTIME ──────────────────────────────────────── */
export const RUNTIME_MODULES = [
  {
    id:             'coleta',
    label:          'Atualização das placas',
    descricao:      'Coleta dados dos pontos em tempo real',
    estado:         OPERATIONAL_STATE.HEALTHY,
    uptime:         '99,97%',
    tempoResposta:  '210ms',
    pontosSincronizados: 847,
    ultimaAtividade:'há 28s',
    tendencia:      'estável',
  },
  {
    id:             'ocupacao',
    label:          'Disponibilidade das placas',
    descricao:      'Monitora disponibilidade e capacidade operacional',
    estado:         OPERATIONAL_STATE.HEALTHY,
    uptime:         '100%',
    tempoResposta:  '87ms',
    pontosSincronizados: 847,
    ultimaAtividade:'há 42s',
    tendencia:      'estável',
  },
  {
    id:             'contratos',
    label:          'Gestão de contratos',
    descricao:      'Verifica vigências, vencimentos e renovações',
    estado:         OPERATIONAL_STATE.WARNING,
    uptime:         '99,80%',
    tempoResposta:  '340ms',
    pontosSincronizados: 143,
    ultimaAtividade:'há 5min',
    tendencia:      'atenção',
  },
  {
    id:             'relatorios',
    label:          'Relatórios gerenciais',
    descricao:      'Consolida dados para relatórios e exportações',
    estado:         OPERATIONAL_STATE.SYNCING,
    uptime:         '99,60%',
    tempoResposta:  '1.200ms',
    pontosSincronizados: 0,
    ultimaAtividade:'há 9min',
    tendencia:      'atualizando',
  },
  {
    id:             'alertas',
    label:          'Central de alertas',
    descricao:      'Monitora e distribui alertas operacionais',
    estado:         OPERATIONAL_STATE.HEALTHY,
    uptime:         '100%',
    tempoResposta:  '55ms',
    pontosSincronizados: null,
    ultimaAtividade:'contínua',
    tendencia:      'estável',
  },
  {
    id:             'regional',
    label:          'Desempenho regional',
    descricao:      'Analisa métricas e ocupação por região',
    estado:         OPERATIONAL_STATE.DEGRADED,
    uptime:         '97,20%',
    tempoResposta:  '890ms',
    pontosSincronizados: 6,
    ultimaAtividade:'há 2min',
    tendencia:      'lento',
  },
];

/* ── GRID REGIONAL OPERACIONAL ───────────────────────────────── */
export const REGIONAL_OPS = [
  {
    id:             'sp',
    label:          'São Paulo',
    sigla:          'SP',
    total:          312,
    ativos:         264,
    disponiveis:    48,
    emManutencao:   8,
    ocupacao:       0.846,
    receitaAtiva:   128400,
    alertas:        1,
    estado:         OPERATIONAL_STATE.HEALTHY,
    prioridade:     'normal',
    tendencia:      'crescimento',
    responsavel:    'Ops SP',
    ultimaSync:     'há 38s',
  },
  {
    id:             'rj',
    label:          'Rio de Janeiro',
    sigla:          'RJ',
    total:          198,
    ativos:         148,
    disponiveis:    50,
    emManutencao:   4,
    ocupacao:       0.747,
    receitaAtiva:   72600,
    alertas:        2,
    estado:         OPERATIONAL_STATE.WARNING,
    prioridade:     'alta',
    tendencia:      'estável',
    responsavel:    'Ops RJ',
    ultimaSync:     'há 1min',
  },
  {
    id:             'mg',
    label:          'Minas Gerais',
    sigla:          'MG',
    total:          124,
    ativos:         88,
    disponiveis:    36,
    emManutencao:   3,
    ocupacao:       0.710,
    receitaAtiva:   43200,
    alertas:        0,
    estado:         OPERATIONAL_STATE.HEALTHY,
    prioridade:     'normal',
    tendencia:      'crescimento',
    responsavel:    'Ops MG',
    ultimaSync:     'há 52s',
  },
  {
    id:             'rs',
    label:          'Rio Grande do Sul',
    sigla:          'RS',
    total:          89,
    ativos:         60,
    disponiveis:    29,
    emManutencao:   2,
    ocupacao:       0.674,
    receitaAtiva:   24800,
    alertas:        1,
    estado:         OPERATIONAL_STATE.DEGRADED,
    prioridade:     'alta',
    tendencia:      'queda',
    responsavel:    'Ops RS',
    ultimaSync:     'há 3min',
  },
  {
    id:             'pr',
    label:          'Paraná',
    sigla:          'PR',
    total:          76,
    ativos:         62,
    disponiveis:    14,
    emManutencao:   1,
    ocupacao:       0.816,
    receitaAtiva:   28400,
    alertas:        0,
    estado:         OPERATIONAL_STATE.HEALTHY,
    prioridade:     'normal',
    tendencia:      'crescimento',
    responsavel:    'Ops PR',
    ultimaSync:     'há 45s',
  },
  {
    id:             'outros',
    label:          'Outras regiões',
    sigla:          '—',
    total:          48,
    ativos:         39,
    disponiveis:    9,
    emManutencao:   0,
    ocupacao:       0.813,
    receitaAtiva:   15800,
    alertas:        0,
    estado:         OPERATIONAL_STATE.HEALTHY,
    prioridade:     'baixa',
    tendencia:      'estável',
    responsavel:    'Ops Geral',
    ultimaSync:     'há 1min',
  },
];

/* ── SYNC STATUS ─────────────────────────────────────────────── */
export const SYNC_STATUS = {
  estado:            OPERATIONAL_STATE.HEALTHY,
  modo:              'automático',
  intervalo:         '30 segundos',
  ultimaSync:        '2026-05-19T09:41:28Z',
  ultimaSyncLabel:   'há 42 segundos',
  proximaSync:       'em 18 segundos',
  totalPontos:       847,
  pontosAtualizados: 844,
  divergencias:      3,
  regioesSincronizadas: 6,
  regioesPendentes:  0,
  detalhes: [
    { regiao: 'São Paulo',        pontos: 312, sincronizados: 311, estado: OPERATIONAL_STATE.HEALTHY   },
    { regiao: 'Rio de Janeiro',   pontos: 198, sincronizados: 198, estado: OPERATIONAL_STATE.HEALTHY   },
    { regiao: 'Minas Gerais',     pontos: 124, sincronizados: 124, estado: OPERATIONAL_STATE.HEALTHY   },
    { regiao: 'Rio Grande do Sul',pontos:  89, sincronizados:  87, estado: OPERATIONAL_STATE.WARNING   },
    { regiao: 'Paraná',           pontos:  76, sincronizados:  76, estado: OPERATIONAL_STATE.HEALTHY   },
    { regiao: 'Outras',           pontos:  48, sincronizados:  48, estado: OPERATIONAL_STATE.HEALTHY   },
  ],
};

/* ── OPERATIONS FEED ─────────────────────────────────────────── */
export const OPERATIONS_FEED = [
  { id:'f01', tipo:'ocupacao',    icone:'check_circle',    label:'SP-1933 ocupado — Campanha Verão 2026',         regiao:'SP', tempo:'agora',     cor:'var(--v4p-success)' },
  { id:'f02', tipo:'alerta',      icone:'warning',         label:'RJ-0412 reportou falha de iluminação',          regiao:'RJ', tempo:'2 min',     cor:'var(--v4p-warning)' },
  { id:'f03', tipo:'liberacao',   icone:'radio_button_unchecked', label:'MG-0301 liberado — fim de campanha',    regiao:'MG', tempo:'5 min',     cor:'var(--v4p-text-3)'  },
  { id:'f04', tipo:'campanha',    icone:'campaign',        label:'PR-0044 nova campanha iniciada — Atacado Sul',  regiao:'PR', tempo:'8 min',     cor:'var(--v4p-accent)'  },
  { id:'f05', tipo:'sync',        icone:'sync',            label:'Sincronização completa — 847 pontos',           regiao:'Todos', tempo:'12 min',  cor:'var(--v4p-accent)'  },
  { id:'f06', tipo:'manutencao',  icone:'build',           label:'MG-0112 retornou da manutenção',               regiao:'MG', tempo:'24 min',    cor:'var(--v4p-success)' },
  { id:'f07', tipo:'ocupacao',    icone:'check_circle',    label:'SP-0891 ocupado — cliente Meridian Media',      regiao:'SP', tempo:'31 min',    cor:'var(--v4p-success)' },
  { id:'f08', tipo:'alerta',      icone:'crisis_alert',    label:'SP-2241 sem sinal há 48h — equipe acionada',    regiao:'SP', tempo:'48 min',    cor:'var(--v4p-danger)'  },
  { id:'f09', tipo:'liberacao',   icone:'radio_button_unchecked','label':'RS-0088 contrato próximo do vencimento', regiao:'RS', tempo:'1h 2min',  cor:'var(--v4p-warning)' },
  { id:'f10', tipo:'campanha',    icone:'campaign',        label:'RJ-0220 nova campanha — anunciante nacional',   regiao:'RJ', tempo:'1h 18min',  cor:'var(--v4p-accent)'  },
  { id:'f11', tipo:'sync',        icone:'sync',            label:'Sincronização automática — RS com divergência', regiao:'RS', tempo:'1h 30min',  cor:'var(--v4p-warning)' },
  { id:'f12', tipo:'ocupacao',    icone:'check_circle',    label:'PR-0215 ocupado — segmento varejo',             regiao:'PR', tempo:'2h',        cor:'var(--v4p-success)' },
];
