import type { MarketplaceCapability, MarketplaceModule } from '../contracts/marketplace.contracts';

export const MARKETPLACE_MODULE_REGISTRY: MarketplaceModule[] = [
  {
    id: 'analytics-suite',
    name: 'Analytics Suite',
    description: 'Camada analítica operacional com BI, relatórios de governança e qualidade.',
    category: 'analytics',
    status: 'available',
    visibility: 'tenant',
    capabilities: ['enterprise-bi', 'governance-reports', 'quality-monitoring', 'legacy-reporting'],
    dependencies: [],
    requirements: ['tenant-context', 'admin.access'],
    scopes: ['admin.access'],
    minimumGovernanceScore: 70,
    minimumQualityScore: 75,
    featureFlags: [{ key: 'marketplace.analytics.enabled', enabled: true, rollout: 'all' }],
  },
  {
    id: 'geo-suite',
    name: 'Geo Intelligence Suite',
    description: 'Capacidades geográficas para segmentação, cobertura e inteligência territorial.',
    category: 'geo',
    status: 'available',
    visibility: 'tenant',
    capabilities: ['geo-intelligence'],
    dependencies: [],
    requirements: ['tenant-context'],
    scopes: ['admin.access'],
    minimumGovernanceScore: 65,
    minimumQualityScore: 65,
    featureFlags: [{ key: 'marketplace.geo.enabled', enabled: true, rollout: 'all' }],
  },
  {
    id: 'export-suite',
    name: 'Export Suite',
    description: 'Exportação interna de datasets operacionais e executivos.',
    category: 'export',
    status: 'available',
    visibility: 'tenant',
    capabilities: ['exports'],
    dependencies: [{ capabilityId: 'enterprise-bi', required: true }],
    requirements: ['tenant-context', 'snapshot-availability'],
    scopes: ['admin.access'],
    minimumGovernanceScore: 70,
    minimumQualityScore: 75,
    featureFlags: [{ key: 'marketplace.export.enabled', enabled: true, rollout: 'all' }],
  },
  {
    id: 'realtime-suite',
    name: 'Realtime Streams',
    description: 'Streams em tempo real para painéis e integrações operacionais.',
    category: 'realtime',
    status: 'beta',
    visibility: 'tenant',
    capabilities: ['realtime-streams'],
    dependencies: [{ capabilityId: 'public-api-bridge', required: false }],
    requirements: ['tenant-context', 'eventing-enabled'],
    scopes: ['admin.access'],
    minimumGovernanceScore: 75,
    minimumQualityScore: 70,
    featureFlags: [{ key: 'marketplace.realtime.beta', enabled: true, rollout: 'beta' }],
  },
  {
    id: 'integration-suite',
    name: 'Integration Suite',
    description: 'Suíte de integrações internas e exposição controlada para parceiros.',
    category: 'integrations',
    status: 'available',
    visibility: 'tenant',
    capabilities: ['public-api-bridge', 'partner-access'],
    dependencies: [],
    requirements: ['tenant-context'],
    scopes: ['admin.access'],
    minimumGovernanceScore: 70,
    minimumQualityScore: 70,
    featureFlags: [{ key: 'marketplace.integrations.enabled', enabled: true, rollout: 'all' }],
  },
  {
    id: 'inventory-suite',
    name: 'Inventory Suite',
    description: 'Capacidades operacionais para inventário e cobertura de mídia.',
    category: 'inventory',
    status: 'available',
    visibility: 'tenant',
    capabilities: ['inventory-health'],
    dependencies: [],
    requirements: ['tenant-context'],
    scopes: ['admin.access'],
    minimumGovernanceScore: 65,
    minimumQualityScore: 70,
    featureFlags: [{ key: 'marketplace.inventory.enabled', enabled: true, rollout: 'all' }],
  },
  {
    id: 'governance-suite',
    name: 'Governance Suite',
    description: 'Visões de conformidade, qualidade e políticas de exposição.',
    category: 'governance',
    status: 'available',
    visibility: 'tenant',
    capabilities: ['quality-monitoring', 'governance-reports', 'legacy-reporting', 'marketplace-automation'],
    dependencies: [{ capabilityId: 'enterprise-bi', required: true }],
    requirements: ['tenant-context', 'quality-snapshot'],
    scopes: ['admin.access'],
    minimumGovernanceScore: 75,
    minimumQualityScore: 75,
    featureFlags: [{ key: 'marketplace.governance.enabled', enabled: true, rollout: 'all' }],
  },
];

export const MARKETPLACE_CAPABILITY_REGISTRY: MarketplaceCapability[] = [
  {
    id: 'enterprise-bi',
    name: 'Enterprise BI',
    description: 'Base analítica executiva para KPIs, painéis e snapshots consolidados.',
    category: 'analytics',
    status: 'available',
    visibility: 'tenant',
    dependencies: [],
    requirements: ['tenant-context'],
    scopes: ['admin.access'],
    minimumGovernanceScore: 70,
    minimumQualityScore: 75,
    featureFlags: [{ key: 'marketplace.analytics.enabled', enabled: true, rollout: 'all' }],
    modules: ['analytics-suite'],
  },
  {
    id: 'geo-intelligence',
    name: 'Geo Intelligence',
    description: 'Capacidade territorial para segmentação geográfica e cobertura.',
    category: 'geo',
    status: 'available',
    visibility: 'tenant',
    dependencies: [],
    requirements: ['tenant-context'],
    scopes: ['admin.access'],
    minimumGovernanceScore: 65,
    minimumQualityScore: 65,
    featureFlags: [{ key: 'marketplace.geo.enabled', enabled: true, rollout: 'all' }],
    modules: ['geo-suite'],
  },
  {
    id: 'exports',
    name: 'Exports',
    description: 'Exportação segura de relatórios e datasets operacionais.',
    category: 'export',
    status: 'available',
    visibility: 'tenant',
    dependencies: [{ capabilityId: 'enterprise-bi', required: true }],
    requirements: ['tenant-context', 'snapshot-availability'],
    scopes: ['admin.access'],
    minimumGovernanceScore: 70,
    minimumQualityScore: 75,
    featureFlags: [{ key: 'marketplace.export.enabled', enabled: true, rollout: 'all' }],
    modules: ['export-suite'],
  },
  {
    id: 'realtime-streams',
    name: 'Realtime Streams',
    description: 'Streams e feeds operacionais em tempo real.',
    category: 'realtime',
    status: 'beta',
    visibility: 'tenant',
    dependencies: [{ capabilityId: 'public-api-bridge', required: false }],
    requirements: ['tenant-context', 'eventing-enabled'],
    scopes: ['admin.access'],
    minimumGovernanceScore: 75,
    minimumQualityScore: 70,
    featureFlags: [{ key: 'marketplace.realtime.beta', enabled: true, rollout: 'beta' }],
    modules: ['realtime-suite'],
  },
  {
    id: 'public-api-bridge',
    name: 'Public API Bridge',
    description: 'Camada de integração controlada para integrações e parceiros.',
    category: 'public-api',
    status: 'available',
    visibility: 'tenant',
    dependencies: [],
    requirements: ['tenant-context'],
    scopes: ['admin.access'],
    minimumGovernanceScore: 70,
    minimumQualityScore: 70,
    featureFlags: [{ key: 'marketplace.integrations.enabled', enabled: true, rollout: 'all' }],
    modules: ['integration-suite'],
  },
  {
    id: 'partner-access',
    name: 'Partner Access',
    description: 'Acesso interno controlado para parceiros e canais externos.',
    category: 'integrations',
    status: 'internal',
    visibility: 'internal',
    dependencies: [{ capabilityId: 'public-api-bridge', required: true }],
    requirements: ['tenant-context', 'partner-approval'],
    scopes: ['admin.access'],
    minimumGovernanceScore: 90,
    minimumQualityScore: 85,
    featureFlags: [{ key: 'marketplace.partner.internal', enabled: true, rollout: 'internal' }],
    modules: ['integration-suite'],
  },
  {
    id: 'quality-monitoring',
    name: 'Quality Monitoring',
    description: 'Monitoramento de qualidade e conformidade de dados.',
    category: 'governance',
    status: 'available',
    visibility: 'tenant',
    dependencies: [{ capabilityId: 'enterprise-bi', required: true }],
    requirements: ['tenant-context', 'quality-snapshot'],
    scopes: ['admin.access'],
    minimumGovernanceScore: 75,
    minimumQualityScore: 80,
    featureFlags: [{ key: 'marketplace.governance.enabled', enabled: true, rollout: 'all' }],
    modules: ['analytics-suite', 'governance-suite'],
  },
  {
    id: 'governance-reports',
    name: 'Governance Reports',
    description: 'Relatórios de governança com trilha de revisão e exposição.',
    category: 'governance',
    status: 'available',
    visibility: 'tenant',
    dependencies: [{ capabilityId: 'enterprise-bi', required: true }],
    requirements: ['tenant-context', 'governance-snapshot'],
    scopes: ['admin.access'],
    minimumGovernanceScore: 80,
    minimumQualityScore: 75,
    featureFlags: [{ key: 'marketplace.governance.enabled', enabled: true, rollout: 'all' }],
    modules: ['analytics-suite', 'governance-suite'],
  },
  {
    id: 'inventory-health',
    name: 'Inventory Health',
    description: 'Saúde do inventário, cobertura e disponibilidade operacional.',
    category: 'inventory',
    status: 'available',
    visibility: 'tenant',
    dependencies: [],
    requirements: ['tenant-context'],
    scopes: ['admin.access'],
    minimumGovernanceScore: 65,
    minimumQualityScore: 70,
    featureFlags: [{ key: 'marketplace.inventory.enabled', enabled: true, rollout: 'all' }],
    modules: ['inventory-suite'],
  },
  {
    id: 'legacy-reporting',
    name: 'Legacy Reporting',
    description: 'Canal legado de relatórios mantido apenas por compatibilidade.',
    category: 'analytics',
    status: 'deprecated',
    visibility: 'restricted',
    dependencies: [],
    requirements: ['tenant-context'],
    scopes: ['admin.access'],
    minimumGovernanceScore: 60,
    minimumQualityScore: 60,
    featureFlags: [{ key: 'marketplace.analytics.enabled', enabled: true, rollout: 'all' }],
    modules: ['analytics-suite'],
  },
  {
    id: 'marketplace-automation',
    name: 'Marketplace Automation',
    description: 'Automação operacional planejada para aprovisionamento futuro.',
    category: 'integrations',
    status: 'planned',
    visibility: 'internal',
    dependencies: [{ capabilityId: 'public-api-bridge', required: true }],
    requirements: ['tenant-context', 'automation-approval'],
    scopes: ['admin.access'],
    minimumGovernanceScore: 95,
    minimumQualityScore: 90,
    featureFlags: [{ key: 'marketplace.automation.planned', enabled: false, rollout: 'internal' }],
    modules: ['integration-suite', 'governance-suite'],
  },
];

export function getMarketplaceModule(moduleId: string): MarketplaceModule | undefined {
  return MARKETPLACE_MODULE_REGISTRY.find((module) => module.id === moduleId);
}

export function getMarketplaceCapability(capabilityId: string): MarketplaceCapability | undefined {
  return MARKETPLACE_CAPABILITY_REGISTRY.find((capability) => capability.id === capabilityId);
}
