/* ═══════════════════════════════════════════════════════════════
   INVENTORY MOCK DATA — V4 PAINEL
   Placas como entidades operacionais vivas.
═══════════════════════════════════════════════════════════════ */
import { OPERATIONAL_STATE } from '../../foundation/operationalStates.js';
import { PRIORITY }          from '../../foundation/priorities.js';
import { SEVERITY }          from '../../foundation/severityLevels.js';

export const BOARD_CATEGORY = {
  PREMIUM_A_PLUS: 'Premium A+',
  PREMIUM_A:      'Premium A',
  STANDARD_B_PLUS:'Standard B+',
  STANDARD_B:     'Standard B',
  ECONOMICO_C:    'Econômico C',
};

export const BOARD_STATUS = {
  OCCUPIED:    'occupied',
  AVAILABLE:   'available',
  MAINTENANCE: 'maintenance',
  RESERVED:    'reserved',
  CRITICAL:    'critical',
};

/* ── BOARDS COMPLETOS ────────────────────────────────────────── */
export const INVENTORY_BOARDS = [
  {
    id:'SP-2241', codigo:'SP-2241', nome:'Paulista — Altura MASP',
    localizacao:'Av. Paulista, 1578 — São Paulo',
    regiao:'São Paulo', siglaRegiao:'SP',
    status: BOARD_STATUS.CRITICAL, estado: OPERATIONAL_STATE.CRITICAL,
    categoria: BOARD_CATEGORY.PREMIUM_A_PLUS,
    ocupacao: 0, ocupado: false,
    receitaEstimada: 4200, receitaFormatada: 'R$ 4.200/mês',
    prioridade: PRIORITY.URGENT,
    diasOcioso: null, vencimento: null,
    ultimaAtividade: 'há 48h — sem sinal',
    campanha: null, cliente: null,
    statusDetalhe: 'Sem comunicação há 48h — verificação em campo acionada',
    recomendacao: 'Verificar equipamento in loco. Campanha aguardando.',
    visibilidade: 'Muito alta', risco: SEVERITY.CRITICAL,
    imageUrl: 'https://picsum.photos/seed/SP2241/400/220',
    thumbnailUrl: 'https://picsum.photos/seed/SP2241/200/110',
    imageAlt: 'Foto da placa SP-2241 — Paulista, altura MASP',
    lat: -23.561684, lng: -46.655981,
  },
  {
    id:'SP-1933', codigo:'SP-1933', nome:'Marginal Pinheiros — km 18',
    localizacao:'Rod. dos Imigrantes, km 18 — São Paulo',
    regiao:'São Paulo', siglaRegiao:'SP',
    status: BOARD_STATUS.OCCUPIED, estado: OPERATIONAL_STATE.HEALTHY,
    categoria: BOARD_CATEGORY.PREMIUM_A_PLUS,
    ocupacao: 1, ocupado: true,
    receitaEstimada: 5200, receitaFormatada: 'R$ 5.200/mês',
    prioridade: PRIORITY.NORMAL,
    diasOcioso: null, vencimento: '2026-06-11',
    ultimaAtividade: 'há 12min',
    campanha: 'Campanha Verão 2026 — Loja X',
    cliente: 'Grupo Fast Moda',
    statusDetalhe: 'Ativo. Campanha com 22 dias restantes.',
    recomendacao: 'Iniciar negociação de renovação em 7 dias.',
    visibilidade: 'Muito alta', risco: SEVERITY.INFO,
    imageUrl: 'https://picsum.photos/seed/SP1933/400/220',
    thumbnailUrl: 'https://picsum.photos/seed/SP1933/200/110',
    imageAlt: 'Foto da placa SP-1933 — Marginal Pinheiros, km 18',
    lat: -23.585, lng: -46.696,
  },
  {
    id:'SP-1089', codigo:'SP-1089', nome:'Marginal Tietê — km 24',
    localizacao:'Marginal Tietê, km 24 — São Paulo',
    regiao:'São Paulo', siglaRegiao:'SP',
    status: BOARD_STATUS.AVAILABLE, estado: OPERATIONAL_STATE.WARNING,
    categoria: BOARD_CATEGORY.PREMIUM_A_PLUS,
    ocupacao: 0, ocupado: false,
    receitaEstimada: 5800, receitaFormatada: 'R$ 5.800/mês',
    prioridade: PRIORITY.HIGH,
    diasOcioso: 12, vencimento: null,
    ultimaAtividade: 'há 12 dias — livre',
    campanha: null, cliente: null,
    statusDetalhe: 'Ocioso há 12 dias em corredor premium.',
    recomendacao: 'Acionar carteira de leads para posição premium.',
    visibilidade: 'Muito alta', risco: SEVERITY.MEDIUM,
    imageUrl: 'https://picsum.photos/seed/SP1089/400/220',
    thumbnailUrl: 'https://picsum.photos/seed/SP1089/200/110',
    imageAlt: 'Foto da placa SP-1089 — Marginal Tietê, km 24',
    lat: -23.531, lng: -46.718,
  },
  {
    id:'SP-0891', codigo:'SP-0891', nome:'Consolação — Metrô',
    localizacao:'R. da Consolação, 2301 — São Paulo',
    regiao:'São Paulo', siglaRegiao:'SP',
    status: BOARD_STATUS.OCCUPIED, estado: OPERATIONAL_STATE.HEALTHY,
    categoria: BOARD_CATEGORY.PREMIUM_A,
    ocupacao: 1, ocupado: true,
    receitaEstimada: 3600, receitaFormatada: 'R$ 3.600/mês',
    prioridade: PRIORITY.NORMAL,
    diasOcioso: null, vencimento: '2026-07-04',
    ultimaAtividade: 'há 31min',
    campanha: 'Lançamento Produto Y',
    cliente: 'Meridian Media / Pharma Brasil',
    statusDetalhe: 'Ativo. 45 dias restantes.',
    recomendacao: 'Alta performance — manter.',
    visibilidade: 'Alta', risco: SEVERITY.INFO,
    imageUrl: 'https://picsum.photos/seed/SP0891/400/220',
    thumbnailUrl: 'https://picsum.photos/seed/SP0891/200/110',
    imageAlt: 'Foto da placa SP-0891 — Consolação, próximo ao Metrô',
    lat: -23.552, lng: -46.660,
  },
  {
    id:'RJ-0412', codigo:'RJ-0412', nome:'Presidente Vargas — Centro',
    localizacao:'Av. Presidente Vargas, 890 — Rio de Janeiro',
    regiao:'Rio de Janeiro', siglaRegiao:'RJ',
    status: BOARD_STATUS.MAINTENANCE, estado: OPERATIONAL_STATE.DEGRADED,
    categoria: BOARD_CATEGORY.PREMIUM_A,
    ocupacao: 0, ocupado: false,
    receitaEstimada: 2800, receitaFormatada: 'R$ 2.800/mês',
    prioridade: PRIORITY.URGENT,
    diasOcioso: null, vencimento: null,
    ultimaAtividade: 'há 41min — falha',
    campanha: null, cliente: null,
    statusDetalhe: 'Falha de iluminação reportada. Manutenção agendada para hoje.',
    recomendacao: 'Manutenção em andamento. Retorno previsto: 48h.',
    visibilidade: 'Alta', risco: SEVERITY.HIGH,
    imageUrl: 'https://picsum.photos/seed/RJ0412/400/220',
    thumbnailUrl: 'https://picsum.photos/seed/RJ0412/200/110',
    imageAlt: 'Foto da placa RJ-0412 — Presidente Vargas, Centro RJ',
    lat: -22.906, lng: -43.176,
  },
  {
    id:'RJ-0220', codigo:'RJ-0220', nome:'Aterro do Flamengo',
    localizacao:'Av. Infante Dom Henrique — Rio de Janeiro',
    regiao:'Rio de Janeiro', siglaRegiao:'RJ',
    status: BOARD_STATUS.OCCUPIED, estado: OPERATIONAL_STATE.HEALTHY,
    categoria: BOARD_CATEGORY.PREMIUM_A,
    ocupacao: 1, ocupado: true,
    receitaEstimada: 4100, receitaFormatada: 'R$ 4.100/mês',
    prioridade: PRIORITY.NORMAL,
    diasOcioso: null, vencimento: '2026-05-28',
    ultimaAtividade: 'há 1h 18min',
    campanha: 'Campanha Nacional Verão',
    cliente: 'Anunciante Nacional X',
    statusDetalhe: 'Ativo. 8 dias restantes.',
    recomendacao: 'Proposta de renovação preparada.',
    visibilidade: 'Muito alta', risco: SEVERITY.LOW,
    imageUrl: 'https://picsum.photos/seed/RJ0220/400/220',
    thumbnailUrl: 'https://picsum.photos/seed/RJ0220/200/110',
    imageAlt: 'Foto da placa RJ-0220 — Aterro do Flamengo',
    lat: -22.929, lng: -43.170,
  },
  {
    id:'RJ-0889', codigo:'RJ-0889', nome:'Barra da Tijuca — Shopping',
    localizacao:'Av. das Américas, 4666 — Rio de Janeiro',
    regiao:'Rio de Janeiro', siglaRegiao:'RJ',
    status: BOARD_STATUS.AVAILABLE, estado: OPERATIONAL_STATE.WARNING,
    categoria: BOARD_CATEGORY.PREMIUM_A,
    ocupacao: 0, ocupado: false,
    receitaEstimada: 4600, receitaFormatada: 'R$ 4.600/mês',
    prioridade: PRIORITY.HIGH,
    diasOcioso: 9, vencimento: null,
    ultimaAtividade: 'há 9 dias — livre',
    campanha: null, cliente: null,
    statusDetalhe: 'Ocioso há 9 dias. Alto potencial sazonalidade verão.',
    recomendacao: 'Contato com agências RJ especialistas em varejo.',
    visibilidade: 'Alta', risco: SEVERITY.MEDIUM,
    imageUrl: 'https://picsum.photos/seed/RJ0889/400/220',
    thumbnailUrl: 'https://picsum.photos/seed/RJ0889/200/110',
    imageAlt: 'Foto da placa RJ-0889 — Barra da Tijuca, próximo ao Shopping',
    lat: -23.000, lng: -43.365,
  },
  {
    id:'MG-0301', codigo:'MG-0301', nome:'Afonso Pena — BH Centro',
    localizacao:'Av. Afonso Pena, 3401 — Belo Horizonte',
    regiao:'Minas Gerais', siglaRegiao:'MG',
    status: BOARD_STATUS.AVAILABLE, estado: OPERATIONAL_STATE.WARNING,
    categoria: BOARD_CATEGORY.STANDARD_B_PLUS,
    ocupacao: 0, ocupado: false,
    receitaEstimada: 3400, receitaFormatada: 'R$ 3.400/mês',
    prioridade: PRIORITY.HIGH,
    diasOcioso: 18, vencimento: null,
    ultimaAtividade: 'há 18 dias — livre',
    campanha: null, cliente: null,
    statusDetalhe: 'Ocioso há 18 dias. Período pré-festivo favorável.',
    recomendacao: 'Acionar carteira de leads BH — segmento varejo e alimentação.',
    visibilidade: 'Alta', risco: SEVERITY.MEDIUM,
    imageUrl: 'https://picsum.photos/seed/MG0301/400/220',
    thumbnailUrl: 'https://picsum.photos/seed/MG0301/200/110',
    imageAlt: 'Foto da placa MG-0301 — Afonso Pena, BH Centro',
    lat: -19.920, lng: -43.938,
  },
  {
    id:'MG-0112', codigo:'MG-0112', nome:'Anel Rodoviário — km 9',
    localizacao:'Anel Rodoviário, km 9 — Belo Horizonte',
    regiao:'Minas Gerais', siglaRegiao:'MG',
    status: BOARD_STATUS.OCCUPIED, estado: OPERATIONAL_STATE.HEALTHY,
    categoria: BOARD_CATEGORY.STANDARD_B_PLUS,
    ocupacao: 1, ocupado: true,
    receitaEstimada: 2800, receitaFormatada: 'R$ 2.800/mês',
    prioridade: PRIORITY.NORMAL,
    diasOcioso: null, vencimento: '2026-06-21',
    ultimaAtividade: 'há 24min',
    campanha: 'Campanha Logística Sul',
    cliente: 'Transportes ABC',
    statusDetalhe: 'Ativo. 32 dias restantes.',
    recomendacao: 'Retornou da manutenção. Acompanhar nas próximas 72h.',
    visibilidade: 'Alta', risco: SEVERITY.INFO,
    imageUrl: 'https://picsum.photos/seed/MG0112/400/220',
    thumbnailUrl: 'https://picsum.photos/seed/MG0112/200/110',
    imageAlt: 'Foto da placa MG-0112 — Anel Rodoviário, km 9',
    lat: -19.945, lng: -43.981,
  },
  {
    id:'RS-0088', codigo:'RS-0088', nome:'Av. Ipiranga — Porto Alegre',
    localizacao:'Av. Ipiranga, 1820 — Porto Alegre',
    regiao:'Rio Grande do Sul', siglaRegiao:'RS',
    status: BOARD_STATUS.RESERVED, estado: OPERATIONAL_STATE.WARNING,
    categoria: BOARD_CATEGORY.STANDARD_B,
    ocupacao: 0, ocupado: false,
    receitaEstimada: 1900, receitaFormatada: 'R$ 1.900/mês',
    prioridade: PRIORITY.HIGH,
    diasOcioso: null, vencimento: '2026-05-23',
    ultimaAtividade: 'há 3 dias',
    campanha: null,
    cliente: 'Renovação pendente',
    statusDetalhe: 'Contrato vence em 3 dias. Aguardando confirmação.',
    recomendacao: 'Contato urgente com cliente para confirmar renovação.',
    visibilidade: 'Média', risco: SEVERITY.HIGH,
    imageUrl: 'https://picsum.photos/seed/RS0088/400/220',
    thumbnailUrl: 'https://picsum.photos/seed/RS0088/200/110',
    imageAlt: 'Foto da placa RS-0088 — Av. Ipiranga, Porto Alegre',
    lat: -30.033, lng: -51.230,
  },
  {
    id:'RS-0044', codigo:'RS-0044', nome:'Freeway — km 12',
    localizacao:'Freeway BR-290, km 12 — Eldorado do Sul',
    regiao:'Rio Grande do Sul', siglaRegiao:'RS',
    status: BOARD_STATUS.AVAILABLE, estado: OPERATIONAL_STATE.WARNING,
    categoria: BOARD_CATEGORY.STANDARD_B,
    ocupacao: 0, ocupado: false,
    receitaEstimada: 2100, receitaFormatada: 'R$ 2.100/mês',
    prioridade: PRIORITY.HIGH,
    diasOcioso: 21, vencimento: null,
    ultimaAtividade: 'há 21 dias — livre',
    campanha: null, cliente: null,
    statusDetalhe: 'Ocioso há 21 dias. Corredor com alta circulação.',
    recomendacao: 'Reduzir preço de entrada para reativar posição.',
    visibilidade: 'Alta', risco: SEVERITY.MEDIUM,
    imageUrl: 'https://picsum.photos/seed/RS0044/400/220',
    thumbnailUrl: 'https://picsum.photos/seed/RS0044/200/110',
    imageAlt: 'Foto da placa RS-0044 — Freeway BR-290, km 12',
    lat: -30.105, lng: -51.561,
  },
  {
    id:'PR-0044', codigo:'PR-0044', nome:'BR-376 — Km 4 Curitiba',
    localizacao:'BR-376, km 4 — São José dos Pinhais',
    regiao:'Paraná', siglaRegiao:'PR',
    status: BOARD_STATUS.OCCUPIED, estado: OPERATIONAL_STATE.HEALTHY,
    categoria: BOARD_CATEGORY.STANDARD_B_PLUS,
    ocupacao: 1, ocupado: true,
    receitaEstimada: 2400, receitaFormatada: 'R$ 2.400/mês',
    prioridade: PRIORITY.NORMAL,
    diasOcioso: null, vencimento: '2026-06-07',
    ultimaAtividade: 'há 8min',
    campanha: 'Campanha Atacado Sul',
    cliente: 'Atacado Boa Vista',
    statusDetalhe: 'Ativo. 18 dias restantes.',
    recomendacao: 'Performance estável. Proposta de expansão disponível.',
    visibilidade: 'Alta', risco: SEVERITY.INFO,
    imageUrl: 'https://picsum.photos/seed/PR0044/400/220',
    thumbnailUrl: 'https://picsum.photos/seed/PR0044/200/110',
    imageAlt: 'Foto da placa PR-0044 — BR-376, km 4, Curitiba',
    lat: -25.575, lng: -49.220,
  },
  {
    id:'PR-0215', codigo:'PR-0215', nome:'BR-376 — Km 91',
    localizacao:'BR-376, km 91 — Ponta Grossa',
    regiao:'Paraná', siglaRegiao:'PR',
    status: BOARD_STATUS.OCCUPIED, estado: OPERATIONAL_STATE.HEALTHY,
    categoria: BOARD_CATEGORY.STANDARD_B,
    ocupacao: 1, ocupado: true,
    receitaEstimada: 2100, receitaFormatada: 'R$ 2.100/mês',
    prioridade: PRIORITY.NORMAL,
    diasOcioso: null, vencimento: '2026-07-19',
    ultimaAtividade: 'há 2h',
    campanha: 'Campanha Varejo Regional',
    cliente: 'Comércio Paraná LTDA',
    statusDetalhe: 'Ativo. Recém ocupado.',
    recomendacao: 'Acompanhar desempenho inicial da campanha.',
    visibilidade: 'Média', risco: SEVERITY.INFO,
    imageUrl: 'https://picsum.photos/seed/PR0215/400/220',
    thumbnailUrl: 'https://picsum.photos/seed/PR0215/200/110',
    imageAlt: 'Foto da placa PR-0215 — BR-376, km 91, Ponta Grossa',
    lat: -25.095, lng: -50.161,
  },
  {
    id:'SP-0340', codigo:'SP-0340', nome:'Interlagos — Av. Sen. Teotônio',
    localizacao:'Av. Sen. Teotônio Vilela, 2001 — São Paulo',
    regiao:'São Paulo', siglaRegiao:'SP',
    status: BOARD_STATUS.OCCUPIED, estado: OPERATIONAL_STATE.HEALTHY,
    categoria: BOARD_CATEGORY.STANDARD_B_PLUS,
    ocupacao: 1, ocupado: true,
    receitaEstimada: 2700, receitaFormatada: 'R$ 2.700/mês',
    prioridade: PRIORITY.NORMAL,
    diasOcioso: null, vencimento: '2026-05-31',
    ultimaAtividade: 'há 2h 30min',
    campanha: 'Campanha Auto Peças',
    cliente: 'AutoPeças Central SP',
    statusDetalhe: 'Ativo. 11 dias restantes.',
    recomendacao: 'Iniciar processo de renovação em 5 dias.',
    visibilidade: 'Média', risco: SEVERITY.LOW,
    imageUrl: 'https://picsum.photos/seed/SP0340/400/220',
    thumbnailUrl: 'https://picsum.photos/seed/SP0340/200/110',
    imageAlt: 'Foto da placa SP-0340 — Interlagos, Av. Sen. Teotônio',
    lat: -23.699, lng: -46.694,
  },
  {
    id:'MG-0445', codigo:'MG-0445', nome:'Contorno — Bairro Savassi',
    localizacao:'Av. do Contorno, 5500 — Belo Horizonte',
    regiao:'Minas Gerais', siglaRegiao:'MG',
    status: BOARD_STATUS.AVAILABLE, estado: OPERATIONAL_STATE.HEALTHY,
    categoria: BOARD_CATEGORY.PREMIUM_A,
    ocupacao: 0, ocupado: false,
    receitaEstimada: 3800, receitaFormatada: 'R$ 3.800/mês',
    prioridade: PRIORITY.NORMAL,
    diasOcioso: 5, vencimento: null,
    ultimaAtividade: 'há 5 dias — livre',
    campanha: null, cliente: null,
    statusDetalhe: 'Recém liberado. Posição premium no Savassi.',
    recomendacao: 'Alta demanda esperada — cotação em andamento.',
    visibilidade: 'Alta', risco: SEVERITY.LOW,
    imageUrl: 'https://picsum.photos/seed/MG0445/400/220',
    thumbnailUrl: 'https://picsum.photos/seed/MG0445/200/110',
    imageAlt: 'Foto da placa MG-0445 — Contorno, Savassi, BH',
    lat: -19.935, lng: -43.936,
  },
];

/* ── RESUMO DO INVENTÁRIO ────────────────────────────────────── */
export const INVENTORY_SUMMARY = {
  total:          847,
  ocupadas:       661,
  disponiveis:    131,
  manutencao:     18,
  reservadas:     37,
  criticas:       3,
  taxaOcupacao:   0.781,
  receitaTotal:   284750,
};

/* ── DISTRIBUIÇÃO DE OCUPAÇÃO ────────────────────────────────── */
export const OCCUPANCY_DISTRIBUTION = [
  { label: 'Ocupadas',     count: 661, pct: 0.781, cor: 'var(--v4p-success)',     icone: 'check_circle' },
  { label: 'Disponíveis',  count: 131, pct: 0.155, cor: 'var(--v4p-accent)',      icone: 'radio_button_unchecked' },
  { label: 'Em manutenção',count:  18, pct: 0.021, cor: 'var(--v4p-warning)',     icone: 'build' },
  { label: 'Reservadas',   count:  37, pct: 0.044, cor: 'var(--v4p-info)',        icone: 'bookmark' },
  { label: 'Críticas',     count:   3, pct: 0.004, cor: 'var(--v4p-danger)',      icone: 'crisis_alert' },
];

/* ── FILTROS DISPONÍVEIS ─────────────────────────────────────── */
export const FILTER_OPTIONS = {
  regiao:    ['Todas', 'São Paulo', 'Rio de Janeiro', 'Minas Gerais', 'Rio Grande do Sul', 'Paraná'],
  status:    ['Todos', 'Ocupado', 'Disponível', 'Manutenção', 'Reservado', 'Crítico'],
  categoria: ['Todas', 'Premium A+', 'Premium A', 'Standard B+', 'Standard B', 'Econômico C'],
  prioridade:['Todas', 'Urgente', 'Alta', 'Normal', 'Baixa'],
};

/* ── DADOS ESTENDIDOS POR PLACA ──────────────────────────────── */
const _makeContracts = (base) => [
  {
    id: `CTR-${base}-001`, cliente: base.c1, campanha: base.p1,
    inicio: base.i1, fim: base.f1, valorMensal: base.v1,
    status: 'closed', renovacao: false, responsavelComercial: base.rc,
  },
  {
    id: `CTR-${base}-002`, cliente: base.c2, campanha: base.p2,
    inicio: base.i2, fim: base.f2, valorMensal: base.v2,
    status: 'closed', renovacao: true, responsavelComercial: base.rc,
  },
  {
    id: `CTR-${base}-003`, cliente: base.c3, campanha: base.p3,
    inicio: base.i3, fim: base.f3, valorMensal: base.v3,
    status: base.s3 ?? 'active', renovacao: false, responsavelComercial: base.rc2 ?? base.rc,
  },
  {
    id: `CTR-${base}-004`, cliente: base.c4, campanha: base.p4,
    inicio: base.i4, fim: base.f4, valorMensal: base.v4,
    status: base.s4 ?? 'pending', renovacao: true, responsavelComercial: base.rc2 ?? base.rc,
  },
];

const _makeActivity = (items) => items.map(([date, type, desc, user]) => ({ date, type, description: desc, user }));

const EXTENDED = {
  'SP-2241': {
    address: 'Av. Paulista, 1578', city: 'São Paulo', uf: 'SP',
    operationalRegion: 'Centro Expandido SP', zone: 'Zona Central',
    referencePoint: 'Em frente ao MASP', estimatedFlow: '180.000 veíc./dia',
    visibilityScore: 10, lighting: 'LED de alta potência', roadDirection: 'Ambos sentidos',
    format: 'Outdoor Digital', dimensions: '9m × 3m', face: 'Dupla face',
    material: 'Estrutura metálica + LED', lastInspection: '2026-04-02', condition: 'Crítico',
    operationalOwner: 'Carlos Menezes',
    recentContracts: [
      { id:'CTR-2241-001', cliente:'Banco Itaú', campanha:'Campanha Fidelidade 2025', inicio:'2025-08-01', fim:'2025-10-31', valorMensal:4200, status:'closed', renovacao:false, responsavelComercial:'Ana Lima' },
      { id:'CTR-2241-002', cliente:'Ambev', campanha:'Verão Brahma 2025', inicio:'2025-11-01', fim:'2026-01-31', valorMensal:4500, status:'closed', renovacao:false, responsavelComercial:'Ana Lima' },
      { id:'CTR-2241-003', cliente:'Nike Brasil', campanha:'Sprint Collection', inicio:'2026-02-01', fim:'2026-03-31', valorMensal:4200, status:'closed', renovacao:false, responsavelComercial:'Pedro Vaz' },
      { id:'CTR-2241-004', cliente:'—', campanha:'Disponível', inicio:'2026-04-01', fim:'—', valorMensal:0, status:'pending', renovacao:false, responsavelComercial:'Pedro Vaz' },
    ],
    activityHistory: _makeActivity([
      ['2026-04-02','inspection','Vistoria técnica realizada — falha de comunicação detectada','Carlos Menezes'],
      ['2026-04-01','status_change','Status alterado para Crítico','Sistema'],
      ['2026-03-31','board_released','Placa liberada ao final da campanha Nike','Pedro Vaz'],
      ['2026-02-01','campaign_activated','Campanha Sprint Collection ativada','Pedro Vaz'],
      ['2026-01-31','contract_renewed','Contrato Ambev encerrado sem renovação','Ana Lima'],
    ]),
    performance: { receitaAcumulada: 189000, taxaOcupacao: 0.74, diasOcupada: 270, diasDisponivel: 95, potencialMensal: 4200, mediaRegiao: 3600 },
    recommendations: {
      comercial: 'Posição nobre com alta visibilidade — retomar prospecção imediatamente após resolução técnica.',
      operacional: 'Verificar módulo de comunicação. Possível falha no controlador principal.',
      risco: 'CRÍTICO — 48h sem sinal. Risco de perda de posição se campanha confirmada.',
      proximaAcao: 'Acionar equipe de campo nas próximas 4h.',
    },
  },
  'SP-1933': {
    address: 'Rod. dos Imigrantes, km 18', city: 'São Paulo', uf: 'SP',
    operationalRegion: 'Corredor Sul SP', zone: 'Zona Sul',
    referencePoint: 'Km 18 sentido Baixada Santista', estimatedFlow: '210.000 veíc./dia',
    visibilityScore: 10, lighting: 'LED bilateral', roadDirection: 'Sentido litoral',
    format: 'Frontlight', dimensions: '14m × 4m', face: 'Face única',
    material: 'Lona impressa alta definição', lastInspection: '2026-04-15', condition: 'Ótimo',
    operationalOwner: 'Roberto Campos',
    recentContracts: [
      { id:'CTR-1933-001', cliente:'Ford Motors', campanha:'Lançamento EcoSport 2025', inicio:'2025-06-01', fim:'2025-08-31', valorMensal:5000, status:'closed', renovacao:false, responsavelComercial:'Fernanda Rocha' },
      { id:'CTR-1933-002', cliente:'iFood', campanha:'Verão iFood 2025', inicio:'2025-09-01', fim:'2025-11-30', valorMensal:4800, status:'closed', renovacao:false, responsavelComercial:'Fernanda Rocha' },
      { id:'CTR-1933-003', cliente:'Grupo Fast Moda', campanha:'Coleção Inverno 2026', inicio:'2026-01-15', fim:'2026-04-20', valorMensal:5200, status:'closed', renovacao:true, responsavelComercial:'Marcos Silva' },
      { id:'CTR-1933-004', cliente:'Grupo Fast Moda', campanha:'Campanha Verão 2026 — Loja X', inicio:'2026-04-21', fim:'2026-06-11', valorMensal:5200, status:'active', renovacao:true, responsavelComercial:'Marcos Silva' },
    ],
    activityHistory: _makeActivity([
      ['2026-04-21','campaign_activated','Campanha Verão 2026 ativada — renovação','Marcos Silva'],
      ['2026-04-20','contract_renewed','Contrato renovado com Grupo Fast Moda','Marcos Silva'],
      ['2026-04-15','inspection','Vistoria preventiva realizada — condição ótima','Roberto Campos'],
      ['2026-01-15','campaign_activated','Coleção Inverno ativada','Fernanda Rocha'],
      ['2025-12-01','registry_update','Dados cadastrais atualizados no sistema','Sistema'],
    ]),
    performance: { receitaAcumulada: 296400, taxaOcupacao: 0.95, diasOcupada: 347, diasDisponivel: 18, potencialMensal: 5200, mediaRegiao: 3600 },
    recommendations: {
      comercial: 'Alta taxa de renovação — cliente fidelizado. Propor pacote anual com desconto.',
      operacional: 'Placa em condição ótima. Próxima vistoria preventiva em 90 dias.',
      risco: 'BAIXO — posição estável, histórico de ocupação excelente.',
      proximaAcao: 'Iniciar negociação de renovação com 7 dias de antecedência (até 04/jun).',
    },
  },
  'SP-1089': {
    address: 'Marginal Tietê, km 24', city: 'São Paulo', uf: 'SP',
    operationalRegion: 'Corredor Norte SP', zone: 'Zona Norte',
    referencePoint: 'Acesso ao Rodoanel Mário Covas', estimatedFlow: '195.000 veíc./dia',
    visibilityScore: 9, lighting: 'LED', roadDirection: 'Sentido Ayrton Senna',
    format: 'Outdoor', dimensions: '9m × 3m', face: 'Dupla face',
    material: 'Estrutura metálica galvanizada', lastInspection: '2026-04-18', condition: 'Bom',
    operationalOwner: 'Luís Henrique',
    recentContracts: [
      { id:'CTR-1089-001', cliente:'Correios', campanha:'Campanha Natal 2025', inicio:'2025-10-01', fim:'2026-01-05', valorMensal:5500, status:'closed', renovacao:false, responsavelComercial:'Juliana Freitas' },
      { id:'CTR-1089-002', cliente:'Samsung', campanha:'Galaxy S25 Launch', inicio:'2025-07-01', fim:'2025-09-30', valorMensal:5800, status:'closed', renovacao:false, responsavelComercial:'Juliana Freitas' },
      { id:'CTR-1089-003', cliente:'Claro Telecom', campanha:'Fibra 1Gb SP', inicio:'2026-01-10', fim:'2026-02-09', valorMensal:5600, status:'closed', renovacao:false, responsavelComercial:'Ricardo Souza' },
      { id:'CTR-1089-004', cliente:'—', campanha:'Disponível', inicio:'2026-02-10', fim:'—', valorMensal:0, status:'pending', renovacao:false, responsavelComercial:'Ricardo Souza' },
    ],
    activityHistory: _makeActivity([
      ['2026-02-10','board_released','Placa liberada após encerramento contrato Claro','Ricardo Souza'],
      ['2026-02-09','status_change','Status alterado para Disponível','Sistema'],
      ['2026-01-10','campaign_activated','Campanha Fibra 1Gb ativada','Ricardo Souza'],
      ['2026-01-06','board_released','Campanha Natal Correios encerrada','Juliana Freitas'],
      ['2025-10-01','campaign_activated','Campanha Natal Correios ativada','Juliana Freitas'],
    ]),
    performance: { receitaAcumulada: 210800, taxaOcupacao: 0.83, diasOcupada: 303, diasDisponivel: 62, potencialMensal: 5800, mediaRegiao: 3600 },
    recommendations: {
      comercial: 'Corredor premium ocioso há 12 dias. Acionar top 5 leads da carteira SP — segmento automotivo e telecom.',
      operacional: 'Estrutura em bom estado. Sem pendências operacionais.',
      risco: 'MÉDIO — perda de receita estimada em R$ 2.320 por semana de ociosidade.',
      proximaAcao: 'Enviar proposta para 3 prospects até amanhã.',
    },
  },
  'SP-0891': {
    address: 'R. da Consolação, 2301', city: 'São Paulo', uf: 'SP',
    operationalRegion: 'Centro Expandido SP', zone: 'Zona Central',
    referencePoint: 'Saída Metrô Consolação', estimatedFlow: '85.000 veíc./dia',
    visibilityScore: 8, lighting: 'LED', roadDirection: 'Ambos sentidos',
    format: 'Frontlight', dimensions: '8m × 3m', face: 'Face única',
    material: 'Lona vinil impressa', lastInspection: '2026-04-20', condition: 'Bom',
    operationalOwner: 'Tatiane Borges',
    recentContracts: [
      { id:'CTR-0891-001', cliente:'Drogasil', campanha:'Saúde em Primeiro 2025', inicio:'2025-05-01', fim:'2025-07-31', valorMensal:3400, status:'closed', renovacao:false, responsavelComercial:'Camila Nunes' },
      { id:'CTR-0891-002', cliente:'Nubank', campanha:'Cartão Roxo SP', inicio:'2025-08-01', fim:'2025-10-31', valorMensal:3600, status:'closed', renovacao:false, responsavelComercial:'Camila Nunes' },
      { id:'CTR-0891-003', cliente:'Meridian Media', campanha:'Pré-campanha Pharma', inicio:'2025-11-01', fim:'2025-12-31', valorMensal:3400, status:'closed', renovacao:true, responsavelComercial:'Bruno Alves' },
      { id:'CTR-0891-004', cliente:'Meridian Media / Pharma Brasil', campanha:'Lançamento Produto Y', inicio:'2026-01-15', fim:'2026-07-04', valorMensal:3600, status:'active', renovacao:true, responsavelComercial:'Bruno Alves' },
    ],
    activityHistory: _makeActivity([
      ['2026-01-15','campaign_activated','Campanha Lançamento Produto Y ativada','Bruno Alves'],
      ['2026-01-10','contract_renewed','Contrato renovado com Meridian Media','Bruno Alves'],
      ['2025-12-31','board_released','Pré-campanha encerrada, sequência confirmada','Camila Nunes'],
      ['2025-11-01','campaign_activated','Pré-campanha Pharma iniciada','Camila Nunes'],
      ['2025-10-31','registry_update','Categoria atualizada para Premium A','Sistema'],
    ]),
    performance: { receitaAcumulada: 147200, taxaOcupacao: 0.91, diasOcupada: 332, diasDisponivel: 33, potencialMensal: 3600, mediaRegiao: 3200 },
    recommendations: {
      comercial: 'Alta performance — manter. Propor expansão para SP-0892 ao mesmo cliente.',
      operacional: 'Placa em bom estado. Monitorar desgaste da lona atual (180 dias em uso).',
      risco: 'BAIXO — contrato ativo com 45 dias restantes.',
      proximaAcao: 'Proposta de renovação já pode ser apresentada.',
    },
  },
  'RJ-0412': {
    address: 'Av. Presidente Vargas, 890', city: 'Rio de Janeiro', uf: 'RJ',
    operationalRegion: 'Centro RJ', zone: 'Zona Central',
    referencePoint: 'Em frente à Central do Brasil', estimatedFlow: '120.000 veíc./dia',
    visibilityScore: 9, lighting: 'Fluorescente (em troca)', roadDirection: 'Sentido Norte',
    format: 'Outdoor', dimensions: '9m × 3m', face: 'Face única',
    material: 'Estrutura metálica', lastInspection: '2026-04-19', condition: 'Em manutenção',
    operationalOwner: 'Eduardo Pinto',
    recentContracts: [
      { id:'CTR-0412-001', cliente:'Claro RJ', campanha:'Fibra Carioca 2025', inicio:'2025-04-01', fim:'2025-06-30', valorMensal:2800, status:'closed', renovacao:false, responsavelComercial:'Vanessa Cruz' },
      { id:'CTR-0412-002', cliente:'TIM Brasil', campanha:'5G Rio', inicio:'2025-07-01', fim:'2025-09-30', valorMensal:2800, status:'closed', renovacao:false, responsavelComercial:'Vanessa Cruz' },
      { id:'CTR-0412-003', cliente:'Banco do Brasil', campanha:'Agro RJ 2025', inicio:'2025-10-01', fim:'2025-12-31', valorMensal:2600, status:'closed', renovacao:false, responsavelComercial:'Diego Monteiro' },
      { id:'CTR-0412-004', cliente:'—', campanha:'Em manutenção', inicio:'2026-01-10', fim:'—', valorMensal:0, status:'pending', renovacao:false, responsavelComercial:'Diego Monteiro' },
    ],
    activityHistory: _makeActivity([
      ['2026-04-19','inspection','Vistoria detectou falha no sistema de iluminação','Eduardo Pinto'],
      ['2026-04-18','status_change','Status alterado para Manutenção','Sistema'],
      ['2026-01-09','board_released','Contrato BB encerrado','Diego Monteiro'],
      ['2025-10-01','campaign_activated','Campanha Agro RJ ativada','Diego Monteiro'],
      ['2025-09-30','registry_update','Troca de iluminação programada para Q2/2026','Vanessa Cruz'],
    ]),
    performance: { receitaAcumulada: 115800, taxaOcupacao: 0.72, diasOcupada: 263, diasDisponivel: 102, potencialMensal: 2800, mediaRegiao: 2900 },
    recommendations: {
      comercial: 'Aguardar conclusão da manutenção antes de iniciar nova prospecção.',
      operacional: 'Trocar sistema de iluminação por LED. Retorno previsto em 48h.',
      risco: 'ALTO — manutenção urgente. Risco de perda de receita mensal.',
      proximaAcao: 'Confirmar data de retorno da equipe técnica (hoje).',
    },
  },
  'RJ-0220': {
    address: 'Av. Infante Dom Henrique, s/n', city: 'Rio de Janeiro', uf: 'RJ',
    operationalRegion: 'Zona Sul RJ', zone: 'Zona Sul',
    referencePoint: 'Aterro do Flamengo, acesso Botafogo', estimatedFlow: '95.000 veíc./dia',
    visibilityScore: 10, lighting: 'LED', roadDirection: 'Sentido Centro',
    format: 'Frontlight', dimensions: '14m × 4,5m', face: 'Dupla face',
    material: 'Estrutura de aço + lona premium', lastInspection: '2026-04-10', condition: 'Ótimo',
    operationalOwner: 'Renata Figueiredo',
    recentContracts: [
      { id:'CTR-0220-001', cliente:'Embraer', campanha:'Brasil que Voa 2025', inicio:'2025-06-01', fim:'2025-08-31', valorMensal:4000, status:'closed', renovacao:false, responsavelComercial:'Igor Mendes' },
      { id:'CTR-0220-002', cliente:'Petrobras', campanha:'Energia Limpa RJ', inicio:'2025-09-01', fim:'2025-11-30', valorMensal:3900, status:'closed', renovacao:false, responsavelComercial:'Igor Mendes' },
      { id:'CTR-0220-003', cliente:'Rede Globo', campanha:'Programação Verão 2026', inicio:'2025-12-01', fim:'2026-02-28', valorMensal:4100, status:'closed', renovacao:false, responsavelComercial:'Patrícia Lima' },
      { id:'CTR-0220-004', cliente:'Anunciante Nacional X', campanha:'Campanha Nacional Verão', inicio:'2026-03-15', fim:'2026-05-28', valorMensal:4100, status:'active', renovacao:false, responsavelComercial:'Patrícia Lima' },
    ],
    activityHistory: _makeActivity([
      ['2026-03-15','campaign_activated','Campanha Nacional Verão ativada','Patrícia Lima'],
      ['2026-03-01','registry_update','Negociação concluída — novo cliente captado','Patrícia Lima'],
      ['2026-02-28','board_released','Programação Globo encerrada','Igor Mendes'],
      ['2025-12-01','campaign_activated','Programação Verão Globo ativada','Igor Mendes'],
      ['2025-10-05','inspection','Vistoria anual realizada — condição ótima','Renata Figueiredo'],
    ]),
    performance: { receitaAcumulada: 192800, taxaOcupacao: 0.93, diasOcupada: 340, diasDisponivel: 25, potencialMensal: 4100, mediaRegiao: 2900 },
    recommendations: {
      comercial: 'Contrato vence em 8 dias — proposta de renovação já deve estar em negociação.',
      operacional: 'Estrutura em estado ótimo. Sem pendências.',
      risco: 'BAIXO — vencimento próximo mas histórico positivo com cliente.',
      proximaAcao: 'Confirmar renovação ou acionar carteira de leads RJ Zona Sul.',
    },
  },
  'RJ-0889': {
    address: 'Av. das Américas, 4666', city: 'Rio de Janeiro', uf: 'RJ',
    operationalRegion: 'Barra da Tijuca RJ', zone: 'Zona Oeste',
    referencePoint: 'Em frente ao BarraShopping', estimatedFlow: '75.000 veíc./dia',
    visibilityScore: 8, lighting: 'LED', roadDirection: 'Sentido Recreio',
    format: 'Outdoor Digital', dimensions: '10m × 3,5m', face: 'Dupla face',
    material: 'Estrutura metálica + painel LED', lastInspection: '2026-04-25', condition: 'Bom',
    operationalOwner: 'Cláudio Barbosa',
    recentContracts: [
      { id:'CTR-0889-001', cliente:'Chanel', campanha:'Fashion Week Rio 2025', inicio:'2025-04-01', fim:'2025-04-30', valorMensal:5200, status:'closed', renovacao:false, responsavelComercial:'Amanda Torres' },
      { id:'CTR-0889-002', cliente:'C&A', campanha:'Verão Barra 2025', inicio:'2025-11-01', fim:'2026-01-31', valorMensal:4800, status:'closed', renovacao:false, responsavelComercial:'Amanda Torres' },
      { id:'CTR-0889-003', cliente:'Localfrio', campanha:'Black Friday RJ', inicio:'2025-10-01', fim:'2025-10-31', valorMensal:4600, status:'closed', renovacao:false, responsavelComercial:'Thiago Ramos' },
      { id:'CTR-0889-004', cliente:'—', campanha:'Disponível', inicio:'2026-02-01', fim:'—', valorMensal:0, status:'pending', renovacao:false, responsavelComercial:'Thiago Ramos' },
    ],
    activityHistory: _makeActivity([
      ['2026-02-01','board_released','Placa liberada após encerramento C&A','Thiago Ramos'],
      ['2025-11-01','campaign_activated','Campanha Verão C&A ativada','Amanda Torres'],
      ['2025-10-31','board_released','Black Friday encerrada','Amanda Torres'],
      ['2025-10-01','campaign_activated','Campanha Black Friday ativada','Thiago Ramos'],
      ['2025-04-01','campaign_activated','Fashion Week Rio ativada','Amanda Torres'],
    ]),
    performance: { receitaAcumulada: 159200, taxaOcupacao: 0.68, diasOcupada: 248, diasDisponivel: 117, potencialMensal: 4600, mediaRegiao: 2900 },
    recommendations: {
      comercial: 'Posição premium em corredor de alto poder aquisitivo. Acionar agências especializadas em varejo e moda.',
      operacional: 'Painel LED em bom estado. Verificar calibração de cores no próximo mês.',
      risco: 'MÉDIO — 9 dias ocioso em posição de alto potencial.',
      proximaAcao: 'Contato com top 3 agências RJ especializadas em moda e varejo.',
    },
  },
  'MG-0301': {
    address: 'Av. Afonso Pena, 3401', city: 'Belo Horizonte', uf: 'MG',
    operationalRegion: 'Centro BH', zone: 'Hipercentro',
    referencePoint: 'Próximo ao Parque Municipal', estimatedFlow: '68.000 veíc./dia',
    visibilityScore: 8, lighting: 'Fluorescente', roadDirection: 'Ambos sentidos',
    format: 'Frontlight', dimensions: '9m × 3m', face: 'Face única',
    material: 'Lona impressa', lastInspection: '2026-04-28', condition: 'Regular',
    operationalOwner: 'Sônia Almeida',
    recentContracts: [
      { id:'CTR-0301-001', cliente:'Casas Bahia', campanha:'Liquidação BH 2025', inicio:'2025-03-01', fim:'2025-05-31', valorMensal:3200, status:'closed', renovacao:false, responsavelComercial:'Felipe Nascimento' },
      { id:'CTR-0301-002', cliente:'Supermercado BH', campanha:'Páscoa BH 2025', inicio:'2025-09-01', fim:'2025-11-30', valorMensal:3100, status:'closed', renovacao:false, responsavelComercial:'Felipe Nascimento' },
      { id:'CTR-0301-003', cliente:'Verdemar', campanha:'Orgânicos BH', inicio:'2025-12-01', fim:'2026-01-31', valorMensal:3200, status:'closed', renovacao:false, responsavelComercial:'Letícia Martins' },
      { id:'CTR-0301-004', cliente:'—', campanha:'Disponível', inicio:'2026-02-01', fim:'—', valorMensal:0, status:'pending', renovacao:false, responsavelComercial:'Letícia Martins' },
    ],
    activityHistory: _makeActivity([
      ['2026-02-01','board_released','Placa liberada após campanha Verdemar','Letícia Martins'],
      ['2026-01-20','registry_update','Condição da lona atualizada — desgaste leve','Sônia Almeida'],
      ['2025-12-01','campaign_activated','Campanha Orgânicos BH ativada','Letícia Martins'],
      ['2025-11-30','board_released','Campanha Supermercado BH encerrada','Felipe Nascimento'],
      ['2025-09-01','campaign_activated','Páscoa BH ativada','Felipe Nascimento'],
    ]),
    performance: { receitaAcumulada: 89600, taxaOcupacao: 0.67, diasOcupada: 245, diasDisponivel: 120, potencialMensal: 3400, mediaRegiao: 2800 },
    recommendations: {
      comercial: 'Período pré-festivo favorável. Acionar carteira BH — varejo e alimentação.',
      operacional: 'Considerar troca de lona na próxima renovação de contrato.',
      risco: 'MÉDIO — 18 dias ocioso. Perda de R$ 2.040/semana.',
      proximaAcao: 'Apresentar oferta para 3 supermercados regionais esta semana.',
    },
  },
  'MG-0112': {
    address: 'Anel Rodoviário, km 9', city: 'Belo Horizonte', uf: 'MG',
    operationalRegion: 'Contorno BH', zone: 'Zona Norte',
    referencePoint: 'Acesso à BR-381 sentido Vitória', estimatedFlow: '90.000 veíc./dia',
    visibilityScore: 8, lighting: 'LED', roadDirection: 'Sentido Vitória',
    format: 'Outdoor', dimensions: '9m × 3m', face: 'Dupla face',
    material: 'Estrutura de concreto + lona', lastInspection: '2026-05-01', condition: 'Bom',
    operationalOwner: 'Wellington Souza',
    recentContracts: [
      { id:'CTR-0112-001', cliente:'Correios MG', campanha:'Logística Natal 2025', inicio:'2025-10-01', fim:'2025-12-31', valorMensal:2600, status:'closed', renovacao:false, responsavelComercial:'Raquel Mendes' },
      { id:'CTR-0112-002', cliente:'Sadia', campanha:'Sabor do Brasil MG', inicio:'2025-07-01', fim:'2025-09-30', valorMensal:2800, status:'closed', renovacao:false, responsavelComercial:'Raquel Mendes' },
      { id:'CTR-0112-003', cliente:'Transportes ABC', campanha:'Frota Sul', inicio:'2026-01-05', fim:'2026-03-04', valorMensal:2700, status:'closed', renovacao:true, responsavelComercial:'Gustavo Lima' },
      { id:'CTR-0112-004', cliente:'Transportes ABC', campanha:'Campanha Logística Sul', inicio:'2026-03-05', fim:'2026-06-21', valorMensal:2800, status:'active', renovacao:true, responsavelComercial:'Gustavo Lima' },
    ],
    activityHistory: _makeActivity([
      ['2026-05-01','inspection','Vistoria pós-manutenção — aprovado','Wellington Souza'],
      ['2026-03-05','campaign_activated','Campanha Logística Sul ativada (renovação)','Gustavo Lima'],
      ['2026-03-04','contract_renewed','Contrato renovado com Transportes ABC','Gustavo Lima'],
      ['2026-01-05','campaign_activated','Campanha Frota Sul iniciada','Raquel Mendes'],
      ['2025-12-31','board_released','Campanha Natal Correios encerrada','Raquel Mendes'],
    ]),
    performance: { receitaAcumulada: 127800, taxaOcupacao: 0.88, diasOcupada: 321, diasDisponivel: 44, potencialMensal: 2800, mediaRegiao: 2800 },
    recommendations: {
      comercial: 'Cliente fidelizado com histórico de renovação. Avaliar upgrade de categoria.',
      operacional: 'Acompanhar placa nas próximas 72h após retorno de manutenção.',
      risco: 'BAIXO — contrato ativo, cliente renovando com frequência.',
      proximaAcao: 'Acompanhamento preventivo em 72h.',
    },
  },
  'RS-0088': {
    address: 'Av. Ipiranga, 1820', city: 'Porto Alegre', uf: 'RS',
    operationalRegion: 'Centro POA', zone: 'Zona Central',
    referencePoint: 'Próximo à PUC-RS', estimatedFlow: '55.000 veíc./dia',
    visibilityScore: 7, lighting: 'LED', roadDirection: 'Sentido Bairro',
    format: 'Frontlight', dimensions: '8m × 3m', face: 'Face única',
    material: 'Lona impressa', lastInspection: '2026-04-20', condition: 'Bom',
    operationalOwner: 'Adriana Pereira',
    recentContracts: [
      { id:'CTR-0088-001', cliente:'PUCRS', campanha:'Vestibular 2026', inicio:'2025-09-01', fim:'2025-11-30', valorMensal:1800, status:'closed', renovacao:false, responsavelComercial:'Marcos Gonçalves' },
      { id:'CTR-0088-002', cliente:'Renner', campanha:'Inverno RS 2025', inicio:'2025-06-01', fim:'2025-08-31', valorMensal:1900, status:'closed', renovacao:false, responsavelComercial:'Marcos Gonçalves' },
      { id:'CTR-0088-003', cliente:'BancoSicredi', campanha:'Crédito Gaúcho', inicio:'2025-12-01', fim:'2026-02-22', valorMensal:1900, status:'closed', renovacao:true, responsavelComercial:'Cristiane Moura' },
      { id:'CTR-0088-004', cliente:'Renovação pendente', campanha:'Proposta em análise', inicio:'2026-02-23', fim:'2026-05-23', valorMensal:1900, status:'pending', renovacao:true, responsavelComercial:'Cristiane Moura' },
    ],
    activityHistory: _makeActivity([
      ['2026-04-20','inspection','Vistoria de rotina realizada','Adriana Pereira'],
      ['2026-02-23','status_change','Status alterado para Reservado','Sistema'],
      ['2026-02-22','contract_renewed','Proposta de renovação enviada ao cliente','Cristiane Moura'],
      ['2025-12-01','campaign_activated','Campanha Crédito Gaúcho ativada','Marcos Gonçalves'],
      ['2025-11-30','board_released','Vestibular PUCRS encerrado','Marcos Gonçalves'],
    ]),
    performance: { receitaAcumulada: 86400, taxaOcupacao: 0.79, diasOcupada: 288, diasDisponivel: 77, potencialMensal: 1900, mediaRegiao: 1800 },
    recommendations: {
      comercial: 'Contato urgente para confirmar renovação (vence em 3 dias).',
      operacional: 'Sem pendências operacionais. Estrutura em bom estado.',
      risco: 'ALTO — contrato vence em 3 dias sem confirmação.',
      proximaAcao: 'Ligar para cliente hoje — confirmação ou liberação imediata.',
    },
  },
  'RS-0044': {
    address: 'Freeway BR-290, km 12', city: 'Eldorado do Sul', uf: 'RS',
    operationalRegion: 'Corredor Freeway RS', zone: 'Grande Porto Alegre',
    referencePoint: 'Km 12 sentido Litoral Gaúcho', estimatedFlow: '70.000 veíc./dia',
    visibilityScore: 8, lighting: 'LED', roadDirection: 'Sentido Litoral',
    format: 'Outdoor', dimensions: '9m × 3m', face: 'Dupla face',
    material: 'Estrutura metálica galvanizada', lastInspection: '2026-04-22', condition: 'Bom',
    operationalOwner: 'Leandro Farias',
    recentContracts: [
      { id:'CTR-0044-001', cliente:'Decathlon RS', campanha:'Esporte Verão 2025', inicio:'2025-11-01', fim:'2026-01-05', valorMensal:2100, status:'closed', renovacao:false, responsavelComercial:'Patrícia Duarte' },
      { id:'CTR-0044-002', cliente:'Chevrolet RS', campanha:'Onix RS', inicio:'2025-08-01', fim:'2025-10-31', valorMensal:2200, status:'closed', renovacao:false, responsavelComercial:'Patrícia Duarte' },
      { id:'CTR-0044-003', cliente:'Coca-Cola RS', campanha:'Verão Gelado', inicio:'2025-05-01', fim:'2025-07-31', valorMensal:2000, status:'closed', renovacao:false, responsavelComercial:'André Correia' },
      { id:'CTR-0044-004', cliente:'—', campanha:'Disponível', inicio:'2026-01-06', fim:'—', valorMensal:0, status:'pending', renovacao:false, responsavelComercial:'André Correia' },
    ],
    activityHistory: _makeActivity([
      ['2026-04-22','inspection','Vistoria preventiva realizada','Leandro Farias'],
      ['2026-01-06','board_released','Campanha Decathlon encerrada','André Correia'],
      ['2025-11-01','campaign_activated','Esporte Verão ativada','Patrícia Duarte'],
      ['2025-10-31','board_released','Campanha Chevrolet encerrada','Patrícia Duarte'],
      ['2025-08-01','campaign_activated','Onix RS ativada','Patrícia Duarte'],
    ]),
    performance: { receitaAcumulada: 104400, taxaOcupacao: 0.75, diasOcupada: 274, diasDisponivel: 91, potencialMensal: 2100, mediaRegiao: 1800 },
    recommendations: {
      comercial: 'Reduzir preço de entrada para reativar posição. Corredor estratégico para turismo e atacado.',
      operacional: 'Estrutura em bom estado. Sem pendências.',
      risco: 'MÉDIO — 21 dias ocioso em corredor de alto fluxo.',
      proximaAcao: 'Oferta especial com desconto de 10% para novo contrato trimestral.',
    },
  },
  'PR-0044': {
    address: 'BR-376, km 4', city: 'São José dos Pinhais', uf: 'PR',
    operationalRegion: 'Grande Curitiba PR', zone: 'Corredor Leste',
    referencePoint: 'Acesso ao Aeroporto Internacional', estimatedFlow: '85.000 veíc./dia',
    visibilityScore: 9, lighting: 'LED', roadDirection: 'Sentido São Paulo',
    format: 'Outdoor', dimensions: '9m × 3m', face: 'Dupla face',
    material: 'Estrutura metálica', lastInspection: '2026-04-25', condition: 'Ótimo',
    operationalOwner: 'Marcelo Ribeiro',
    recentContracts: [
      { id:'CTR-PR044-001', cliente:'Volvo Trucks', campanha:'Frota Sul 2025', inicio:'2025-06-01', fim:'2025-08-31', valorMensal:2400, status:'closed', renovacao:false, responsavelComercial:'Daniela Costa' },
      { id:'CTR-PR044-002', cliente:'Azul Linhas Aéreas', campanha:'Voe Curitiba', inicio:'2025-09-01', fim:'2025-11-30', valorMensal:2500, status:'closed', renovacao:false, responsavelComercial:'Daniela Costa' },
      { id:'CTR-PR044-003', cliente:'Cacau Show', campanha:'Chocolates Páscoa 2026', inicio:'2025-12-01', fim:'2026-03-05', valorMensal:2400, status:'closed', renovacao:false, responsavelComercial:'Hugo Fernandes' },
      { id:'CTR-PR044-004', cliente:'Atacado Boa Vista', campanha:'Campanha Atacado Sul', inicio:'2026-03-06', fim:'2026-06-07', valorMensal:2400, status:'active', renovacao:false, responsavelComercial:'Hugo Fernandes' },
    ],
    activityHistory: _makeActivity([
      ['2026-04-25','inspection','Vistoria preventiva — condição ótima','Marcelo Ribeiro'],
      ['2026-03-06','campaign_activated','Campanha Atacado Sul ativada','Hugo Fernandes'],
      ['2026-03-05','board_released','Campanha Cacau Show encerrada','Hugo Fernandes'],
      ['2025-12-01','campaign_activated','Chocolates Páscoa 2026 ativada','Daniela Costa'],
      ['2025-11-30','board_released','Voe Curitiba encerrada','Daniela Costa'],
    ]),
    performance: { receitaAcumulada: 98400, taxaOcupacao: 0.90, diasOcupada: 329, diasDisponivel: 36, potencialMensal: 2400, mediaRegiao: 2200 },
    recommendations: {
      comercial: 'Performance estável. Proposta de expansão para PR-0045 disponível.',
      operacional: 'Placa em condição ótima. Próxima vistoria em 60 dias.',
      risco: 'BAIXO — contrato ativo com 18 dias restantes.',
      proximaAcao: 'Apresentar proposta de expansão de frota ao cliente.',
    },
  },
  'PR-0215': {
    address: 'BR-376, km 91', city: 'Ponta Grossa', uf: 'PR',
    operationalRegion: 'Interior PR', zone: 'Corredor Centro-Leste',
    referencePoint: 'Saída km 91 sentido Paranaguá', estimatedFlow: '55.000 veíc./dia',
    visibilityScore: 7, lighting: 'LED', roadDirection: 'Sentido Paranaguá',
    format: 'Outdoor', dimensions: '9m × 3m', face: 'Face única',
    material: 'Lona impressa', lastInspection: '2026-04-28', condition: 'Bom',
    operationalOwner: 'Sérgio Batista',
    recentContracts: [
      { id:'CTR-0215-001', cliente:'Klabin', campanha:'Klabin Papel PR', inicio:'2025-07-01', fim:'2025-09-30', valorMensal:2000, status:'closed', renovacao:false, responsavelComercial:'Vanessa Porto' },
      { id:'CTR-0215-002', cliente:'Copel', campanha:'Energia PR 2025', inicio:'2025-10-01', fim:'2025-12-31', valorMensal:2100, status:'closed', renovacao:false, responsavelComercial:'Vanessa Porto' },
      { id:'CTR-0215-003', cliente:'Cosan', campanha:'Combustível Raízen Interior', inicio:'2026-01-10', fim:'2026-03-09', valorMensal:2000, status:'closed', renovacao:false, responsavelComercial:'Tiago Barros' },
      { id:'CTR-0215-004', cliente:'Comércio Paraná LTDA', campanha:'Campanha Varejo Regional', inicio:'2026-03-10', fim:'2026-07-19', valorMensal:2100, status:'active', renovacao:false, responsavelComercial:'Tiago Barros' },
    ],
    activityHistory: _makeActivity([
      ['2026-04-28','inspection','Vistoria de rotina realizada','Sérgio Batista'],
      ['2026-03-10','campaign_activated','Campanha Varejo Regional ativada','Tiago Barros'],
      ['2026-03-09','board_released','Campanha Cosan encerrada','Tiago Barros'],
      ['2026-01-10','campaign_activated','Combustível Raízen ativada','Vanessa Porto'],
      ['2025-12-31','board_released','Energia PR encerrada','Vanessa Porto'],
    ]),
    performance: { receitaAcumulada: 84200, taxaOcupacao: 0.82, diasOcupada: 299, diasDisponivel: 66, potencialMensal: 2100, mediaRegiao: 2200 },
    recommendations: {
      comercial: 'Contrato recente. Acompanhar desempenho inicial da campanha.',
      operacional: 'Placa em bom estado. Monitorar lona nos próximos 60 dias.',
      risco: 'BAIXO — contrato ativo recém-iniciado.',
      proximaAcao: 'Relatório de início de campanha em 15 dias.',
    },
  },
  'SP-0340': {
    address: 'Av. Sen. Teotônio Vilela, 2001', city: 'São Paulo', uf: 'SP',
    operationalRegion: 'Zona Sul SP — Interlagos', zone: 'Zona Sul',
    referencePoint: 'Próximo ao Autódromo de Interlagos', estimatedFlow: '60.000 veíc./dia',
    visibilityScore: 7, lighting: 'LED', roadDirection: 'Sentido Centro',
    format: 'Frontlight', dimensions: '9m × 3m', face: 'Face única',
    material: 'Lona impressa digital', lastInspection: '2026-04-20', condition: 'Bom',
    operationalOwner: 'Adriano Fonseca',
    recentContracts: [
      { id:'CTR-0340-001', cliente:'Formula E', campanha:'E-Prix São Paulo 2025', inicio:'2025-03-01', fim:'2025-04-30', valorMensal:3200, status:'closed', renovacao:false, responsavelComercial:'Priscila Neves' },
      { id:'CTR-0340-002', cliente:'Bridgestone', campanha:'Pneus Interlagos', inicio:'2025-08-01', fim:'2025-10-31', valorMensal:2800, status:'closed', renovacao:false, responsavelComercial:'Priscila Neves' },
      { id:'CTR-0340-003', cliente:'Shell', campanha:'Combustível Performance SP', inicio:'2025-11-01', fim:'2026-01-31', valorMensal:2700, status:'closed', renovacao:false, responsavelComercial:'Renato Costa' },
      { id:'CTR-0340-004', cliente:'AutoPeças Central SP', campanha:'Campanha Auto Peças', inicio:'2026-02-01', fim:'2026-05-31', valorMensal:2700, status:'active', renovacao:false, responsavelComercial:'Renato Costa' },
    ],
    activityHistory: _makeActivity([
      ['2026-04-20','inspection','Vistoria preventiva realizada','Adriano Fonseca'],
      ['2026-02-01','campaign_activated','Campanha Auto Peças ativada','Renato Costa'],
      ['2026-01-31','board_released','Shell encerrada','Renato Costa'],
      ['2025-11-01','campaign_activated','Combustível Performance ativada','Priscila Neves'],
      ['2025-10-31','board_released','Bridgestone encerrada','Priscila Neves'],
    ]),
    performance: { receitaAcumulada: 112400, taxaOcupacao: 0.86, diasOcupada: 314, diasDisponivel: 51, potencialMensal: 2700, mediaRegiao: 3600 },
    recommendations: {
      comercial: 'Posição estratégica em época de corridas. Mapear calendário motorsport para campanhas temáticas.',
      operacional: 'Placa em bom estado. Próxima revisão em 60 dias.',
      risco: 'BAIXO — contrato ativo com 11 dias restantes.',
      proximaAcao: 'Iniciar renovação em 5 dias — avaliar proposta premium para período de corridas.',
    },
  },
  'MG-0445': {
    address: 'Av. do Contorno, 5500', city: 'Belo Horizonte', uf: 'MG',
    operationalRegion: 'Savassi / Lourdes BH', zone: 'Zona Sul',
    referencePoint: 'Acesso ao Bairro Savassi', estimatedFlow: '65.000 veíc./dia',
    visibilityScore: 9, lighting: 'LED', roadDirection: 'Sentido Centro',
    format: 'Frontlight', dimensions: '10m × 4m', face: 'Dupla face',
    material: 'Estrutura de concreto + lona premium', lastInspection: '2026-05-10', condition: 'Ótimo',
    operationalOwner: 'Fernanda Couto',
    recentContracts: [
      { id:'CTR-0445-001', cliente:'Prada', campanha:'Coleção Outono BH', inicio:'2025-04-01', fim:'2025-06-30', valorMensal:4200, status:'closed', renovacao:false, responsavelComercial:'Cintia Lopes' },
      { id:'CTR-0445-002', cliente:'Unimed BH', campanha:'Saúde em Foco 2025', inicio:'2025-07-01', fim:'2025-09-30', valorMensal:3800, status:'closed', renovacao:false, responsavelComercial:'Cintia Lopes' },
      { id:'CTR-0445-003', cliente:'TOTVS', campanha:'Tecnologia BH', inicio:'2025-10-01', fim:'2026-01-14', valorMensal:3900, status:'closed', renovacao:false, responsavelComercial:'Jonas Faria' },
      { id:'CTR-0445-004', cliente:'—', campanha:'Disponível', inicio:'2026-01-15', fim:'—', valorMensal:0, status:'pending', renovacao:false, responsavelComercial:'Jonas Faria' },
    ],
    activityHistory: _makeActivity([
      ['2026-05-10','inspection','Vistoria pós-liberação — condição ótima','Fernanda Couto'],
      ['2026-01-15','board_released','Placa liberada — TOTVS encerrou sem renovar','Jonas Faria'],
      ['2025-10-01','campaign_activated','Tecnologia BH ativada','Jonas Faria'],
      ['2025-09-30','board_released','Unimed BH encerrada','Cintia Lopes'],
      ['2025-07-01','campaign_activated','Saúde em Foco ativada','Cintia Lopes'],
    ]),
    performance: { receitaAcumulada: 173600, taxaOcupacao: 0.87, diasOcupada: 318, diasDisponivel: 47, potencialMensal: 3800, mediaRegiao: 2800 },
    recommendations: {
      comercial: 'Alta demanda esperada no Savassi — cotação já em andamento com 2 prospects.',
      operacional: 'Placa em condição ótima. Pronta para nova campanha imediatamente.',
      risco: 'BAIXO — posição premium recém liberada, histórico forte.',
      proximaAcao: 'Fechar cotação em andamento nos próximos 2 dias.',
    },
  },
};

export function getExtendedBoard(board) {
  const ext = EXTENDED[board.id] ?? {};
  return { ...board, ...ext };
}
